course/lesson_00_the_setup/README.md
course/lesson_00_the_setup/hello_world.py
course/lesson_00_the_setup/importable_module.py

Lesson zero again, without information overload.

Draft lesson zero, hello world version.

---

students/grzegorz_bajorski/lesson_00_the_setup/hello_world.py

Grzegorz.bajorski/lesson 00 the setup

---

README.md
course/lesson_00_the_setup/README.md

More detailed reference materials on how to sync fork with master repository

Upstream repo setup links added

---

students/baginski_przemek/lesson_00_the_setup/hello_world.py

Lesson 00 (the setup) first pull request
@jedzej @adziu

Przemek.baginski/lesson 00 the setup

---

students/biegon_piotr/lesson_00_the_setup/hello_world.py

Piotr.biegon/lesson 00 the setup

---

course/lesson_00_the_setup/README.md

Aligning branching convention with directories naming convention

lesson 0 instruction update

---

students/jarosz_natalia/lesson_00_the_setup/hello_world.py

Natalia.jarosz/lesson 00 the setup

---

students/piechowski.michal/lesson_00_the_setup/hello_world.py

Michal.piechowski/lesson 00 the setup

---

students/swietczak_monika/lesson_00_the_setup/hello_world.py

Monika.swietczak/lesson 00 the setup

---

course/lesson_03_functions/README.md
course/lesson_03_functions/calculator.py

A little bit different approach to refactoring exercise for lesson 03 (alternative to Janusz proposal in #27)

Lesson 03 exercise proposal - badly organized calculator

---

students/semko_krzysztof/lesson_00_the_setup/hello_world.py

Semko krzysztof/lesson 00 the setup

---

students/halas_maciek/lesson_00_the_setup/hello_world.py

pretty commit message

---

students/bec_lukasz/lesson_01_basics/README.md
students/bec_lukasz/lesson_01_basics/apple_sharing.py
students/bec_lukasz/lesson_01_basics/area_of_right_angled_triangle.py
students/bec_lukasz/lesson_01_basics/car_route.py
students/bec_lukasz/lesson_01_basics/clock_face_1.py
students/bec_lukasz/lesson_01_basics/digital_clock.py
students/bec_lukasz/lesson_01_basics/first_digit_after_decimal_point.py
students/bec_lukasz/lesson_01_basics/fractional_part.py
students/bec_lukasz/lesson_01_basics/hello_harry.py
students/bec_lukasz/lesson_01_basics/last_digit_of_integer.py
students/bec_lukasz/lesson_01_basics/previous_and_next.py
students/bec_lukasz/lesson_01_basics/school_desks.py
students/bec_lukasz/lesson_01_basics/sum_of_digits.py
students/bec_lukasz/lesson_01_basics/sum_of_three_numbers.py
students/bec_lukasz/lesson_01_basics/tens_digit.py
students/bec_lukasz/lesson_01_basics/total_cost.py

Siema @zamber 
pull request z lesson 01 gotowy

Add lesson_01_basics folder with 15 .py files

---

students/karbowniczyn_tomasz/lesson_00_the_setup/README.md
students/karbowniczyn_tomasz/lesson_00_the_setup/importable_module.py

Add lesson 0 files

---

course/lesson_04_unit_testing/README.md

Proposal for lesson 04. Please review

Add tasks to lesson 04

---

students/ryba_paula/lesson_01_basics/apple_sharing.py
students/ryba_paula/lesson_01_basics/area_of_right-angled_triangle.py
students/ryba_paula/lesson_01_basics/car_route.py
students/ryba_paula/lesson_01_basics/clock_face1.py
students/ryba_paula/lesson_01_basics/digital_clock.py
students/ryba_paula/lesson_01_basics/first_digit_after_decimal_point.py
students/ryba_paula/lesson_01_basics/fractional_part.py
students/ryba_paula/lesson_01_basics/hello_harry.py
students/ryba_paula/lesson_01_basics/last_digit_of_integer.py
students/ryba_paula/lesson_01_basics/previous_and_next.py
students/ryba_paula/lesson_01_basics/school_desks.py
students/ryba_paula/lesson_01_basics/sum_of_digits.py
students/ryba_paula/lesson_01_basics/sum_of_three_numbers.py
students/ryba_paula/lesson_01_basics/tens_digit.py
students/ryba_paula/lesson_01_basics/total_cost.py

@kadilak83 
lesson_01_basics - done

add all practice projects from lesson_01_basics

---

students/stachowska_agata/lesson_00_the_setup/hello_world.py

Agata.stachowska/lesson 00 the setup

---

students/wachulec_maria/lesson_00_the_setup/hello_world.py

Wachulec maria/lesson 00 the setup

---

students/bedkowska_julita/lesson_00_the_setup/hello_world.py

Tomek diakow tieto/lesson 00 the setup

---

students/kaczmarek_katarzyna/lesson_00_the_setup/hello_world.py

@kadilak83 - Can you check it, please?

Lesson 00 the setup - Katarzyna Kaczmarek

---

students/marta_herezo/lesson_00_the_setup/hello_world.py

@tomekDiakowTieto Hi, I've created the requested changes on my repo. Please check it.

Created directory for Marta Herezo

---

students/axel_nowaczyk/lesson_00_the_setup/hello_world.py

lesson 00 the setup

---

students/grzegorz_bajorski/lesson_01_python_basic/apple_sharing.py
students/grzegorz_bajorski/lesson_01_python_basic/area_of_rihgt_angled_triangle.py
students/grzegorz_bajorski/lesson_01_python_basic/car_route.py
students/grzegorz_bajorski/lesson_01_python_basic/clock_face.py
students/grzegorz_bajorski/lesson_01_python_basic/digital_clock.py
students/grzegorz_bajorski/lesson_01_python_basic/first_digits_after_decimal_point.py
students/grzegorz_bajorski/lesson_01_python_basic/fractional_part.py
students/grzegorz_bajorski/lesson_01_python_basic/hallo_harry.py
students/grzegorz_bajorski/lesson_01_python_basic/last_digit_of_intiger.py
students/grzegorz_bajorski/lesson_01_python_basic/previous_and_next.py
students/grzegorz_bajorski/lesson_01_python_basic/school_desks.py
students/grzegorz_bajorski/lesson_01_python_basic/sum_of_digits.py
students/grzegorz_bajorski/lesson_01_python_basic/sum_of_three_numbers.py
students/grzegorz_bajorski/lesson_01_python_basic/tens_digit.py
students/grzegorz_bajorski/lesson_01_python_basic/total_cost.py

All practice added
Signed-off-by: Grzegorz Bajorski <Grzegorz.Bajorski@tieto.com>

Lesson 01 python basic

---

students/piechowski.michal/lesson_01_basics/apple_sharing.py
students/piechowski.michal/lesson_01_basics/area_of_right_angled_triangle.py
students/piechowski.michal/lesson_01_basics/car_route.py
students/piechowski.michal/lesson_01_basics/clock_face_1.py
students/piechowski.michal/lesson_01_basics/clock_face_2.py
students/piechowski.michal/lesson_01_basics/digital_clock.py
students/piechowski.michal/lesson_01_basics/first_digit_after_decimal_point.py
students/piechowski.michal/lesson_01_basics/fractional_part.py
students/piechowski.michal/lesson_01_basics/hello_harry.py
students/piechowski.michal/lesson_01_basics/last_digit_of_integer.py
students/piechowski.michal/lesson_01_basics/previous_and_next.py
students/piechowski.michal/lesson_01_basics/school_desks.py
students/piechowski.michal/lesson_01_basics/sum_of_digits.py
students/piechowski.michal/lesson_01_basics/sum_of_three_numbers.py
students/piechowski.michal/lesson_01_basics/tens_digit.py
students/piechowski.michal/lesson_01_basics/total_cost.py

@kadilak83 please review lesson_01

Add lesson_01 exercises

---

students/sikorski_marcin/Lesson_1_-_Python_basics.py

@kadilak83 Lesson 1 - ready to review

Lesson 1 solutions

---

students/swietczak_monika/lesson_01_basics/apple_sharing.py
students/swietczak_monika/lesson_01_basics/area_of_right_angled_triangle.py
students/swietczak_monika/lesson_01_basics/car_route.py
students/swietczak_monika/lesson_01_basics/clock_face.py
students/swietczak_monika/lesson_01_basics/digital_clock.py
students/swietczak_monika/lesson_01_basics/first_digit_after_decimal_point.py
students/swietczak_monika/lesson_01_basics/fractional_part.py
students/swietczak_monika/lesson_01_basics/hello_harry.py
students/swietczak_monika/lesson_01_basics/last_digit.py
students/swietczak_monika/lesson_01_basics/previous_and_next.py
students/swietczak_monika/lesson_01_basics/school_desks.py
students/swietczak_monika/lesson_01_basics/sum_of_digits.py
students/swietczak_monika/lesson_01_basics/sum_of_three_numbers.py
students/swietczak_monika/lesson_01_basics/tens_digit.py
students/swietczak_monika/lesson_01_basics/total_cost.py

Added lesson_01_basics practice projects

---

course/lesson_00_the_setup/README.md

I add small update into workflow, because there was few problems with creating new branches.

Lesson 0 update - workflow update

---

students/slawinski_amadeusz/lesson_01_basics/1.01_sum_of_three_numbers.py
students/slawinski_amadeusz/lesson_01_basics/1.02_area_of_right-angled_triangle.py
students/slawinski_amadeusz/lesson_01_basics/1.03_hello_harry.py
students/slawinski_amadeusz/lesson_01_basics/1.04_apple_sharing.py
students/slawinski_amadeusz/lesson_01_basics/1.05_previous_and_next.py
students/slawinski_amadeusz/lesson_01_basics/1.06_school_desks.py
students/slawinski_amadeusz/lesson_01_basics/2.01_last_digit_of_integer.py
students/slawinski_amadeusz/lesson_01_basics/2.02_tens_digit.py
students/slawinski_amadeusz/lesson_01_basics/2.03_sum_of_digits.py
students/slawinski_amadeusz/lesson_01_basics/2.04_fractional_part.py
students/slawinski_amadeusz/lesson_01_basics/2.05_first_digit_after_decimal_point.py
students/slawinski_amadeusz/lesson_01_basics/2.06_car_route.py
students/slawinski_amadeusz/lesson_01_basics/2.07_digital_clock.py
students/slawinski_amadeusz/lesson_01_basics/2.08_total_cost.py
students/slawinski_amadeusz/lesson_01_basics/2.09_clock_face_1.py

complete lesson 1 tasks

---

students/adam_wulw/lesson_01_python_basics/apple_sharing.py
students/adam_wulw/lesson_01_python_basics/area_of_right_angle_triangle.py
students/adam_wulw/lesson_01_python_basics/car_route.py
students/adam_wulw/lesson_01_python_basics/clock_face.py
students/adam_wulw/lesson_01_python_basics/digital_clock.py
students/adam_wulw/lesson_01_python_basics/first_dig_after_dec_point.py
students/adam_wulw/lesson_01_python_basics/fractional_part.py
students/adam_wulw/lesson_01_python_basics/hello_harry.py
students/adam_wulw/lesson_01_python_basics/last_digit_of_int.py
students/adam_wulw/lesson_01_python_basics/previous_and_next.py
students/adam_wulw/lesson_01_python_basics/school_desk.py
students/adam_wulw/lesson_01_python_basics/sum_of_digits.py
students/adam_wulw/lesson_01_python_basics/sum_of_three_numbers.py
students/adam_wulw/lesson_01_python_basics/tens_digit.py
students/adam_wulw/lesson_01_python_basics/total_cost.py

All lesson 1

---

students/axel_nowaczyk/lesson_01_basics/Car_route.py
students/axel_nowaczyk/lesson_01_basics/Clock_face_-_1.py
students/axel_nowaczyk/lesson_01_basics/Digital_clock.py
students/axel_nowaczyk/lesson_01_basics/First_digit_after_decimal_point.py
students/axel_nowaczyk/lesson_01_basics/Fractional_part.py
students/axel_nowaczyk/lesson_01_basics/Hello,_Harry!.py
students/axel_nowaczyk/lesson_01_basics/Last_digit_of_integer.py
students/axel_nowaczyk/lesson_01_basics/Sum_of_digits.py
students/axel_nowaczyk/lesson_01_basics/Tens_digit.py
students/axel_nowaczyk/lesson_01_basics/Total_cost.py
students/axel_nowaczyk/lesson_01_basics/apple_sharing.py
students/axel_nowaczyk/lesson_01_basics/area_of_right-angled_triangle.py
students/axel_nowaczyk/lesson_01_basics/previous_and_next.py
students/axel_nowaczyk/lesson_01_basics/school_desks.py
students/axel_nowaczyk/lesson_01_basics/sum_of_three_numbers.py

lesson 01 finished

---

students/kulesza_monika/lesson_01_02/Lesson.py
students/kulesza_monika/lesson_01_02/Lesson_02.py

Lesson 01/02

---

students/baker_glenn/README.md
students/baker_glenn/importable_module.py
students/baker_glenn/lesson_1_scripts/class_desks.py
students/baker_glenn/lesson_1_scripts/greeting.py
students/baker_glenn/lesson_1_scripts/previous_next.py
students/baker_glenn/lesson_1_scripts/right_angled_tri.py
students/baker_glenn/lesson_1_scripts/students _apples.py
students/baker_glenn/lesson_1_scripts/sum_3_no.py
students/baker_glenn/lesson_2_scripts/clock_hand.py
students/baker_glenn/lesson_2_scripts/cupcakes.py
students/baker_glenn/lesson_2_scripts/days_to_destination.py
students/baker_glenn/lesson_2_scripts/digital_clock.py
students/baker_glenn/lesson_2_scripts/first_digit_after_decimal.py
students/baker_glenn/lesson_2_scripts/fractional.py
students/baker_glenn/lesson_2_scripts/last_digit.py
students/baker_glenn/lesson_2_scripts/sum_3_digits.py
students/baker_glenn/lesson_2_scripts/tens.py

Scripts for snakify Lesson 1 & 2 for Lesson 1 - Python basics

---

students/skowronski_rafal/.gitignore
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_01.py
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_02.py
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_03.py
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_04.py
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_05.py
students/skowronski_rafal/lesson_01_basics/lesson_01/problem_06.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_01.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_02.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_03.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_04.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_05.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_06.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_07.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_08.py
students/skowronski_rafal/lesson_01_basics/lesson_02/problem_09.py

@tomekDiakowTieto lesson 01 done

Tomek diakow tieto/lesson 01 basics

---

students/nartowska_karina/lesson_01_basics/README.md
students/nartowska_karina/lesson_01_basics/apple_sharing.py
students/nartowska_karina/lesson_01_basics/area_of_right_angled_triangle.py
students/nartowska_karina/lesson_01_basics/car_route.py
students/nartowska_karina/lesson_01_basics/clock_face_1.py
students/nartowska_karina/lesson_01_basics/digital_clock.py
students/nartowska_karina/lesson_01_basics/first_digit_after_decimal_point.py
students/nartowska_karina/lesson_01_basics/fractional_part.py
students/nartowska_karina/lesson_01_basics/hello_harry.py
students/nartowska_karina/lesson_01_basics/last_digit_of_integer.py
students/nartowska_karina/lesson_01_basics/previous_and_next.py
students/nartowska_karina/lesson_01_basics/school_desks.py
students/nartowska_karina/lesson_01_basics/sum_of_digits.py
students/nartowska_karina/lesson_01_basics/sum_of_three_numbers.py
students/nartowska_karina/lesson_01_basics/tens_digit.py
students/nartowska_karina/lesson_01_basics/total_cost.py

Lesson 01 - 15 tasks

---

students/synowiec_krzysztof/lesson_02_flow_control/adding_factorials.py
students/synowiec_krzysztof/lesson_02_flow_control/bishop_moves.py
students/synowiec_krzysztof/lesson_02_flow_control/chocolate_bar.py
students/synowiec_krzysztof/lesson_02_flow_control/factorial.py
students/synowiec_krzysztof/lesson_02_flow_control/knight_move.py
students/synowiec_krzysztof/lesson_02_flow_control/ladder.py
students/synowiec_krzysztof/lesson_02_flow_control/leap_year.py
students/synowiec_krzysztof/lesson_02_flow_control/lost_card.py
students/synowiec_krzysztof/lesson_02_flow_control/queen_move.py
students/synowiec_krzysztof/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/synowiec_krzysztof/lesson_02_flow_control/the_number_of_zeros.py
students/synowiec_krzysztof/lesson_02_flow_control/the_second_maximum.py

Lesson_02 solutions

---

students/zelichowski_michal/lesson_01_python_basics/apple_sharing.py
students/zelichowski_michal/lesson_01_python_basics/area_of_right-angled_triangle.py
students/zelichowski_michal/lesson_01_python_basics/car_route.py
students/zelichowski_michal/lesson_01_python_basics/clock_face_1.py
students/zelichowski_michal/lesson_01_python_basics/digital_clock.py
students/zelichowski_michal/lesson_01_python_basics/first_digit_after_decimal_point.py
students/zelichowski_michal/lesson_01_python_basics/fractional_part.py
students/zelichowski_michal/lesson_01_python_basics/hello_harry.py
students/zelichowski_michal/lesson_01_python_basics/last_digit_of_integer.py
students/zelichowski_michal/lesson_01_python_basics/previous_and_next.py
students/zelichowski_michal/lesson_01_python_basics/school_desks.py
students/zelichowski_michal/lesson_01_python_basics/sum_of_digits.py
students/zelichowski_michal/lesson_01_python_basics/sum_of_three_numbers.py
students/zelichowski_michal/lesson_01_python_basics/tens_digit.py
students/zelichowski_michal/lesson_01_python_basics/total_cost.py

Lesson 01 commits

---

students/podsiadly_robert/lesson_00_the_setup/hello_world.py

Please let me take part in your course

Robert pod/lesson 00 the setup

---

students/biegon_piotr/lesson_02_flow_control/adding_factorials.py
students/biegon_piotr/lesson_02_flow_control/bishop_moves.py
students/biegon_piotr/lesson_02_flow_control/chocolate_bar.py
students/biegon_piotr/lesson_02_flow_control/factorial.py
students/biegon_piotr/lesson_02_flow_control/knight_move.py
students/biegon_piotr/lesson_02_flow_control/ladder.py
students/biegon_piotr/lesson_02_flow_control/leap_year.py
students/biegon_piotr/lesson_02_flow_control/lost_card.py
students/biegon_piotr/lesson_02_flow_control/queen_move.py
students/biegon_piotr/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/biegon_piotr/lesson_02_flow_control/the_number_of_zeros.py
students/biegon_piotr/lesson_02_flow_control/the_second_maximum.py

Tasks from Lesson_02

---

students/mariusz_michalczyk/lesson_01_basics/Apple_sharing.py
students/mariusz_michalczyk/lesson_01_basics/Area_of_right_angled_triangle.py
students/mariusz_michalczyk/lesson_01_basics/Car_route.py
students/mariusz_michalczyk/lesson_01_basics/Digital_clock.py
students/mariusz_michalczyk/lesson_01_basics/First_digit_after_decimal_point.py
students/mariusz_michalczyk/lesson_01_basics/Fractional_part.py
students/mariusz_michalczyk/lesson_01_basics/Hello_Harry.py
students/mariusz_michalczyk/lesson_01_basics/Last_digit_of_integer.py
students/mariusz_michalczyk/lesson_01_basics/Previous_and_next.py
students/mariusz_michalczyk/lesson_01_basics/School_desks_with_math.py
students/mariusz_michalczyk/lesson_01_basics/School_desks_without_math.py
students/mariusz_michalczyk/lesson_01_basics/Sum_of_digits.py
students/mariusz_michalczyk/lesson_01_basics/Sum_of_three_numbers.py
students/mariusz_michalczyk/lesson_01_basics/Tens_digit.py
students/mariusz_michalczyk/lesson_01_basics/Total_cost.py

Add excersises of lesson_01_basics

---

students/grzegorz_bajorski/lesson_02_flow_control/adding_factorials.py
students/grzegorz_bajorski/lesson_02_flow_control/bishop_move.py
students/grzegorz_bajorski/lesson_02_flow_control/chocolate_bar.py
students/grzegorz_bajorski/lesson_02_flow_control/factorial.py
students/grzegorz_bajorski/lesson_02_flow_control/knight_move.py
students/grzegorz_bajorski/lesson_02_flow_control/ladder.py
students/grzegorz_bajorski/lesson_02_flow_control/leap_year.py
students/grzegorz_bajorski/lesson_02_flow_control/lost_card.py
students/grzegorz_bajorski/lesson_02_flow_control/queen_move.py
students/grzegorz_bajorski/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/grzegorz_bajorski/lesson_02_flow_control/the_number_of_zero.py
students/grzegorz_bajorski/lesson_02_flow_control/the_second_maximum.py

Signed-off-by: Grzegorz Bajorski <Grzegorz.Bajorski@tieto.com>

Add files to lesson 2

---

.stickler.yml
students/wachulec_maria/lesson_01_basics/apple_sharing.py
students/wachulec_maria/lesson_01_basics/area_of_right-angled_triangle.py
students/wachulec_maria/lesson_01_basics/car_route.py
students/wachulec_maria/lesson_01_basics/clock_face_1.py
students/wachulec_maria/lesson_01_basics/digital_clock.py
students/wachulec_maria/lesson_01_basics/first_digit_after_decimal_point.py
students/wachulec_maria/lesson_01_basics/fractional_part.py
students/wachulec_maria/lesson_01_basics/hello_harry.py
students/wachulec_maria/lesson_01_basics/last_digit_of_integer.py
students/wachulec_maria/lesson_01_basics/previous_and_next.py
students/wachulec_maria/lesson_01_basics/school_desks.py
students/wachulec_maria/lesson_01_basics/sum_of_digits.py
students/wachulec_maria/lesson_01_basics/sum_of_three_numbers.py
students/wachulec_maria/lesson_01_basics/tens_digit.py
students/wachulec_maria/lesson_01_basics/total_cost.py

Finished lesson_01

---

students/sendecki_andrzej/lesson_01_basics/apple_sharing.py
students/sendecki_andrzej/lesson_01_basics/area_of_right-angled_triangle.py
students/sendecki_andrzej/lesson_01_basics/car_route.py
students/sendecki_andrzej/lesson_01_basics/clock_face-1.py
students/sendecki_andrzej/lesson_01_basics/digital_clock.py
students/sendecki_andrzej/lesson_01_basics/first_digit_after_decimal_point.py
students/sendecki_andrzej/lesson_01_basics/fractional_part.py
students/sendecki_andrzej/lesson_01_basics/hello_harry.py
students/sendecki_andrzej/lesson_01_basics/last_digit_of_integer.py
students/sendecki_andrzej/lesson_01_basics/previous_and_next.py
students/sendecki_andrzej/lesson_01_basics/school_desks.py
students/sendecki_andrzej/lesson_01_basics/sum_of_digits.py
students/sendecki_andrzej/lesson_01_basics/sum_of_three_numbers.py
students/sendecki_andrzej/lesson_01_basics/tens_digit.py
students/sendecki_andrzej/lesson_01_basics/total_cost.py

6 exercises of Snakify/Lesson 1
9 exercises of Snakify/Lesson 2

lesson_01: lesson 01 exercises

---

students/urtnowski_daniel/lesson_01_basics/Snakify_L1.py
students/urtnowski_daniel/lesson_01_basics/Snakify_L2.py

@jedzej The lesson 01 finished, please review

Adding solutions for: lesson 01 basics

---

students/pietrewicz_bartosz/lesson_01_basics/1_1.py
students/pietrewicz_bartosz/lesson_01_basics/1_2.py
students/pietrewicz_bartosz/lesson_01_basics/1_3.py
students/pietrewicz_bartosz/lesson_01_basics/1_4.py
students/pietrewicz_bartosz/lesson_01_basics/1_5.py
students/pietrewicz_bartosz/lesson_01_basics/1_6.py
students/pietrewicz_bartosz/lesson_01_basics/2_1.py
students/pietrewicz_bartosz/lesson_01_basics/2_2.py
students/pietrewicz_bartosz/lesson_01_basics/2_3.py
students/pietrewicz_bartosz/lesson_01_basics/2_4.py
students/pietrewicz_bartosz/lesson_01_basics/2_5.py
students/pietrewicz_bartosz/lesson_01_basics/2_6.py
students/pietrewicz_bartosz/lesson_01_basics/2_7.py
students/pietrewicz_bartosz/lesson_01_basics/2_8.py
students/pietrewicz_bartosz/lesson_01_basics/2_9.py

Solutions for problems on Snakify: 1-6 for lesson 1 and 1-9 for lesson 2.
@gradopaw please review

Solutions of problems from lesson 1

---

students/Hebdowska_Grazyna/lesson_00_the_setup/hello_world.py
students/axel_nowaczyk/lesson_00_the_setup/hello_world.py
students/chylak_malgorzata/lesson_00_the_setup/hello_world.py
students/kosarzewski_maciej/lesson_00_the_setup/hello_world.py
students/marta_herezo/lesson_00_the_setup/hello_world.py
students/sendecki_andrzej/lesson_00_the_setup/hello_world.py
students/surowiec_marek/lesson_00_the_setup/hello_world.py
students/wielgus_daniel/hello_world.py

This reverts commit df6fdd79c861ecc13d86867c965d8b5439835f60.

Recovery after PR#89

---

students/jakielczyk_miroslaw/lesson_02_flow_control/Lesson_02_part1.py
students/jakielczyk_miroslaw/lesson_02_flow_control/Lesson_02_part2.py
students/jakielczyk_miroslaw/lesson_02_flow_control/Lesson_02_part3.py

three parts for lesson_02+flow_control

---

students/synowiec_krzysztof/lesson_03_functions/calculator.py
students/synowiec_krzysztof/lesson_03_functions/exponentiation.py
students/synowiec_krzysztof/lesson_03_functions/fibonacci_numbers.py
students/synowiec_krzysztof/lesson_03_functions/negative_exponent.py
students/synowiec_krzysztof/lesson_03_functions/the_length_of_the_segment.py

Lesson 3 solutions

---

students/urtnowski_daniel/lesson_02_flow_control/Snakify_L3.py
students/urtnowski_daniel/lesson_02_flow_control/Snakify_L4.py
students/urtnowski_daniel/lesson_02_flow_control/Snakify_L6.py

@jedzej lesson 2 finished, please review

Adding solutions for: lesson 02 flow control

---

students/lakatorz_izaak/lesson_02_flow_control/adding_factorials.py
students/lakatorz_izaak/lesson_02_flow_control/bishop_moves.py
students/lakatorz_izaak/lesson_02_flow_control/chocolate_bar.py
students/lakatorz_izaak/lesson_02_flow_control/equal_to_maximum.py
students/lakatorz_izaak/lesson_02_flow_control/factorial.py
students/lakatorz_izaak/lesson_02_flow_control/knight_move.py
students/lakatorz_izaak/lesson_02_flow_control/ladder.py
students/lakatorz_izaak/lesson_02_flow_control/leap_year.py
students/lakatorz_izaak/lesson_02_flow_control/lost_card.py
students/lakatorz_izaak/lesson_02_flow_control/number_of_zeros.py
students/lakatorz_izaak/lesson_02_flow_control/queen_move.py
students/lakatorz_izaak/lesson_02_flow_control/the_second_maximum.py

Solved lesson_02 problems

---

students/karbowniczyn_tomasz/lesson_01_basics/Area_of_right-angled_triangle.py
students/karbowniczyn_tomasz/lesson_01_basics/HelloHarry.py
students/karbowniczyn_tomasz/lesson_01_basics/apple_sharing.py
students/karbowniczyn_tomasz/lesson_01_basics/car_route.py
students/karbowniczyn_tomasz/lesson_01_basics/clock_face1.py
students/karbowniczyn_tomasz/lesson_01_basics/digital_clock.py
students/karbowniczyn_tomasz/lesson_01_basics/first_digit_after_dectimal_point.py
students/karbowniczyn_tomasz/lesson_01_basics/fractional_part.py
students/karbowniczyn_tomasz/lesson_01_basics/last_Digit_of_int.py
students/karbowniczyn_tomasz/lesson_01_basics/next_prev.py
students/karbowniczyn_tomasz/lesson_01_basics/school_desk.py
students/karbowniczyn_tomasz/lesson_01_basics/sum_digits.py
students/karbowniczyn_tomasz/lesson_01_basics/sum_of_3_numbers.py
students/karbowniczyn_tomasz/lesson_01_basics/tens_digit.py
students/karbowniczyn_tomasz/lesson_01_basics/total_cost.py

Signed-off-by: Karbowniczyn Tomasz <tomasz.karbowniczyn@tieto.com>

add lesson_01_basics files

---

students/semko_krzysztof/lesson_02_flow_control/adding_factorials.py
students/semko_krzysztof/lesson_02_flow_control/bishop_moves.py
students/semko_krzysztof/lesson_02_flow_control/chocolate_bar.py
students/semko_krzysztof/lesson_02_flow_control/factorial.py
students/semko_krzysztof/lesson_02_flow_control/knight_move.py
students/semko_krzysztof/lesson_02_flow_control/ladder.py
students/semko_krzysztof/lesson_02_flow_control/leap_year.py
students/semko_krzysztof/lesson_02_flow_control/lost_card.py
students/semko_krzysztof/lesson_02_flow_control/queen_move.py
students/semko_krzysztof/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/semko_krzysztof/lesson_02_flow_control/the_number_of_zeros.py
students/semko_krzysztof/lesson_02_flow_control/the_second_maximum.py

@jedrzej
Niektóre zadania są straszliwie uproszczone (głównie lost_card.py)...

Semko krzysztof/lesson 02 flow control

---

students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_01.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_02.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_03.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_04.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_05.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_06.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_07.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_08.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_09.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IFN_10.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_01.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_02.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_03.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_04.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_05.py
students/piotrowski_stanislaw/lesson_01_basics/L1_IPN_06.py

@kadilak83 Lesson 01 completed.

Lesson 01 completed - adding py files

---

students/pietrewicz_bartosz/lesson_02_flow_control/Adding_factorials.py
students/pietrewicz_bartosz/lesson_02_flow_control/Bishop_moves.py
students/pietrewicz_bartosz/lesson_02_flow_control/Chocolate_bar.py
students/pietrewicz_bartosz/lesson_02_flow_control/Factorial.py
students/pietrewicz_bartosz/lesson_02_flow_control/Knight_move.py
students/pietrewicz_bartosz/lesson_02_flow_control/Ladder.py
students/pietrewicz_bartosz/lesson_02_flow_control/Leap_year.py
students/pietrewicz_bartosz/lesson_02_flow_control/Lost_card.py
students/pietrewicz_bartosz/lesson_02_flow_control/Queen_move.py
students/pietrewicz_bartosz/lesson_02_flow_control/The_number_of_elements_equal_to_the_maximum.py
students/pietrewicz_bartosz/lesson_02_flow_control/The_number_of_zeros.py
students/pietrewicz_bartosz/lesson_02_flow_control/The_second_maximum.py

Solutions of the problems from lesson 2

---

course/lesson_04_unit_testing/README.md

Some folks have problem with mocking input()

Clarify first task for lesson 04

---

students/piechowski.michal/lesson_02_flow_control/adding_factorials.py
students/piechowski.michal/lesson_02_flow_control/bishop_moves.py
students/piechowski.michal/lesson_02_flow_control/chocolate_bar.py
students/piechowski.michal/lesson_02_flow_control/factorial.py
students/piechowski.michal/lesson_02_flow_control/knight_move.py
students/piechowski.michal/lesson_02_flow_control/ladder.py
students/piechowski.michal/lesson_02_flow_control/leap_year.py
students/piechowski.michal/lesson_02_flow_control/lost_card.py
students/piechowski.michal/lesson_02_flow_control/queen_move.py
students/piechowski.michal/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/piechowski.michal/lesson_02_flow_control/the_number_of_zeros.py
students/piechowski.michal/lesson_02_flow_control/the_second_maximum.py

Add lesson_02 exercises

---

students/halas_maciek/lesson_01/lesson_1.py

First part of lesson 1

---

students/slupek_bartosz/lesson_02_flow_control/Adding_factorials.py
students/slupek_bartosz/lesson_02_flow_control/Bishop_moves.py
students/slupek_bartosz/lesson_02_flow_control/Chocolate_bar.py
students/slupek_bartosz/lesson_02_flow_control/Factorials.py
students/slupek_bartosz/lesson_02_flow_control/Knight_move.py
students/slupek_bartosz/lesson_02_flow_control/Ladder.py
students/slupek_bartosz/lesson_02_flow_control/Leap_year.py
students/slupek_bartosz/lesson_02_flow_control/Lost_cards.py
students/slupek_bartosz/lesson_02_flow_control/Queen_move.py
students/slupek_bartosz/lesson_02_flow_control/The_number_of_elements_equal_to_the_maximum.py
students/slupek_bartosz/lesson_02_flow_control/The_number_of_zeros.py
students/slupek_bartosz/lesson_02_flow_control/The_second_maximum.py

add solutions for lesson 02

---

students/piotrowski_stanislaw/lesson_02_flow_control/bishop_move.py
students/piotrowski_stanislaw/lesson_02_flow_control/chocolate.py
students/piotrowski_stanislaw/lesson_02_flow_control/factorial.py
students/piotrowski_stanislaw/lesson_02_flow_control/how_many_zeroes.py
students/piotrowski_stanislaw/lesson_02_flow_control/knight_move.py
students/piotrowski_stanislaw/lesson_02_flow_control/ladder.py
students/piotrowski_stanislaw/lesson_02_flow_control/leap_year.py
students/piotrowski_stanislaw/lesson_02_flow_control/lost_card.py
students/piotrowski_stanislaw/lesson_02_flow_control/queen_move.py
students/piotrowski_stanislaw/lesson_02_flow_control/seq_num_maximal.py
students/piotrowski_stanislaw/lesson_02_flow_control/seq_second_max.py
students/piotrowski_stanislaw/lesson_02_flow_control/sum_of_factorials.py

@kadilak83 Lesson 02 completed.

Lesson 02 completed - adding py files

---

students/wachulec_maria/lesson_02_flow_control/adding_factorials.py
students/wachulec_maria/lesson_02_flow_control/bishop_moves.py
students/wachulec_maria/lesson_02_flow_control/chocolate_bar.py
students/wachulec_maria/lesson_02_flow_control/factorial.py
students/wachulec_maria/lesson_02_flow_control/knight_move.py
students/wachulec_maria/lesson_02_flow_control/ladder.py
students/wachulec_maria/lesson_02_flow_control/leap_year.py
students/wachulec_maria/lesson_02_flow_control/lost_card.py
students/wachulec_maria/lesson_02_flow_control/queen_move.py
students/wachulec_maria/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/wachulec_maria/lesson_02_flow_control/the_number_of_zeros.py
students/wachulec_maria/lesson_02_flow_control/the_second_maximum.py

Lesson 2 completed

---

students/olszewski_bartosz/lesson_02_flow_control/The_number_of_elements_equal_to_the_maximum.py
students/olszewski_bartosz/lesson_02_flow_control/The_second_maximum.py
students/olszewski_bartosz/lesson_02_flow_control/adding_factorials.py
students/olszewski_bartosz/lesson_02_flow_control/bishop_moves.py
students/olszewski_bartosz/lesson_02_flow_control/chocolate_bar.py
students/olszewski_bartosz/lesson_02_flow_control/factorial.py
students/olszewski_bartosz/lesson_02_flow_control/knight_move.py
students/olszewski_bartosz/lesson_02_flow_control/ladder.py
students/olszewski_bartosz/lesson_02_flow_control/leap_year.py
students/olszewski_bartosz/lesson_02_flow_control/queen_move.py
students/olszewski_bartosz/lesson_02_flow_control/sum_cards.py
students/olszewski_bartosz/lesson_02_flow_control/the_number_of_zeros.py

@kamwar  Please check lesson02

Lesson 02 Flow control done

---

students/synowiec_krzysztof/lesson_03_functions/the_collatz_sequence.py

Lesson 3 The Collatz sequence

---

students/kosarzewski_maciej/lesson_02_flow_control/adding_factorials.py
students/kosarzewski_maciej/lesson_02_flow_control/bishop_moves.py
students/kosarzewski_maciej/lesson_02_flow_control/chocolate_bar.py
students/kosarzewski_maciej/lesson_02_flow_control/factorial.py
students/kosarzewski_maciej/lesson_02_flow_control/knight_move.py
students/kosarzewski_maciej/lesson_02_flow_control/ladder.py
students/kosarzewski_maciej/lesson_02_flow_control/leap_year.py
students/kosarzewski_maciej/lesson_02_flow_control/lost_card.py
students/kosarzewski_maciej/lesson_02_flow_control/queen_move.py
students/kosarzewski_maciej/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/kosarzewski_maciej/lesson_02_flow_control/the_number_of_zeros.py
students/kosarzewski_maciej/lesson_02_flow_control/the_second_maximum.py

Lesson 2: flow control

---

students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_01.py
students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_02.py
students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_03.py
students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_04.py
students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_05.py
students/piatkowska_anna/lesson_01_basics/Lesson1/ex01_06.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_01.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_02.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_03.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_04.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_05.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_06.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_07.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_08.py
students/piatkowska_anna/lesson_01_basics/Lesson2/ex02_09.py

- Snakify lesson1 problems 1-6
- Snakify lesson2 problems 1-9
@zamber Could you review it, please?

Add Snakify problems solutions

---

students/jakielczyk_miroslaw/lesson_03_functions/Collatz_Sequence.py
students/jakielczyk_miroslaw/lesson_03_functions/Exponentiation.py
students/jakielczyk_miroslaw/lesson_03_functions/FibonacciNumbers.py
students/jakielczyk_miroslaw/lesson_03_functions/InputValidation.py
students/jakielczyk_miroslaw/lesson_03_functions/NegativeExponent.py
students/jakielczyk_miroslaw/lesson_03_functions/TheLengthOfTheSegment.py
students/jakielczyk_miroslaw/lesson_03_functions/kalkulator.py

tasks for lesson_03_functions

---

students/nartowska_karina/lesson_02_flow_control/README.md
students/nartowska_karina/lesson_02_flow_control/adding_factorials.py
students/nartowska_karina/lesson_02_flow_control/bishop_moves.py
students/nartowska_karina/lesson_02_flow_control/chocolate_bar.py
students/nartowska_karina/lesson_02_flow_control/factorial.py
students/nartowska_karina/lesson_02_flow_control/knight_move.py
students/nartowska_karina/lesson_02_flow_control/ladder.py
students/nartowska_karina/lesson_02_flow_control/leap_year.py
students/nartowska_karina/lesson_02_flow_control/lost_card.py
students/nartowska_karina/lesson_02_flow_control/queen_move.py
students/nartowska_karina/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/nartowska_karina/lesson_02_flow_control/the_number_of_zeros.py
students/nartowska_karina/lesson_02_flow_control/the_second_maximum.py

Lesson 02 - 12 tasks

---

course/lesson_04_unit_testing/README.md

I've added short description at the beginning, additional reference material about and changed the practice projects.
I've changed exercise 3 from adding factorials to more testable fibonacci number, since there are no functions in adding factorials implementation.

lesson 4 update proposal

---

students/ryba_paula/lesson_03_functions/calculator.py
students/ryba_paula/lesson_03_functions/exponentiation.py
students/ryba_paula/lesson_03_functions/fibonacci_numbers.py
students/ryba_paula/lesson_03_functions/negative_exponent.py
students/ryba_paula/lesson_03_functions/the_collatz_sequence_and_validation.py
students/ryba_paula/lesson_03_functions/the_length_of_the_segment.py

@kadilak83 proszę o sprawdzenie :)

Add lesson_03_functions solutions

---

students/pluciennik_edyta/lesson_02_flow_control/adding_factorials.py
students/pluciennik_edyta/lesson_02_flow_control/bishop_moves.py
students/pluciennik_edyta/lesson_02_flow_control/chocolate_bar.py
students/pluciennik_edyta/lesson_02_flow_control/elements_equal_to_the_maximum.py
students/pluciennik_edyta/lesson_02_flow_control/factorial.py
students/pluciennik_edyta/lesson_02_flow_control/knight_moves.py
students/pluciennik_edyta/lesson_02_flow_control/ladder.py
students/pluciennik_edyta/lesson_02_flow_control/leap_year.py
students/pluciennik_edyta/lesson_02_flow_control/lost_card.py
students/pluciennik_edyta/lesson_02_flow_control/queen_moves.py
students/pluciennik_edyta/lesson_02_flow_control/the_numbers_of_zeros.py
students/pluciennik_edyta/lesson_02_flow_control/the_second_maximum.py

Lesson 2: flow control 

---

students/stachowska_agata/lesson_02_flow_control/adding_factorials.py
students/stachowska_agata/lesson_02_flow_control/bishop_moves.py
students/stachowska_agata/lesson_02_flow_control/chocolate_bar.py
students/stachowska_agata/lesson_02_flow_control/factorial.py
students/stachowska_agata/lesson_02_flow_control/knight_move.py
students/stachowska_agata/lesson_02_flow_control/ladder.py
students/stachowska_agata/lesson_02_flow_control/leap_year.py
students/stachowska_agata/lesson_02_flow_control/lost_card.py
students/stachowska_agata/lesson_02_flow_control/num_maximal.py
students/stachowska_agata/lesson_02_flow_control/number_of_zeros.py
students/stachowska_agata/lesson_02_flow_control/queen_moves.py
students/stachowska_agata/lesson_02_flow_control/second_maximum.py

@kamwar lesson02 ready to check

add lesson02 files

---

students/adam_wulw/lesson_02_flow_control/adding_factorials.py
students/adam_wulw/lesson_02_flow_control/bishop_moves.py
students/adam_wulw/lesson_02_flow_control/chocolate_bar.py
students/adam_wulw/lesson_02_flow_control/factorial.py
students/adam_wulw/lesson_02_flow_control/king_move.py
students/adam_wulw/lesson_02_flow_control/lader.py
students/adam_wulw/lesson_02_flow_control/leap_year.py
students/adam_wulw/lesson_02_flow_control/lost_card.py
students/adam_wulw/lesson_02_flow_control/queen_move.py
students/adam_wulw/lesson_02_flow_control/the_number_of_zeros.py
students/adam_wulw/lesson_02_flow_control/the_second_maximun.py

All lesson 2

---

students/medrek_tomasz/lesson_02_flow_control/adding_factorials.py
students/medrek_tomasz/lesson_02_flow_control/bishop_moves.py
students/medrek_tomasz/lesson_02_flow_control/chocolate_bar.py
students/medrek_tomasz/lesson_02_flow_control/delete_a_character.py
students/medrek_tomasz/lesson_02_flow_control/delete_every_third_character.py
students/medrek_tomasz/lesson_02_flow_control/factorial.py
students/medrek_tomasz/lesson_02_flow_control/how_many_zeroes.py
students/medrek_tomasz/lesson_02_flow_control/knight_move.py
students/medrek_tomasz/lesson_02_flow_control/ladder.py
students/medrek_tomasz/lesson_02_flow_control/leap_year.py
students/medrek_tomasz/lesson_02_flow_control/lost_card.py
students/medrek_tomasz/lesson_02_flow_control/queen_move.py
students/medrek_tomasz/lesson_02_flow_control/replace_the_substring.py
students/medrek_tomasz/lesson_02_flow_control/replace_within_the_fragment.py
students/medrek_tomasz/lesson_02_flow_control/reverse_the_fragment.py

@tomekDiakowTieto , please take a look.
BR
Tomasz

added lesson 2: flow control

---

students/skowronski_rafal/.gitignore
students/skowronski_rafal/lesson_02_flow_control/lesson_03/chess_game.py
students/skowronski_rafal/lesson_02_flow_control/lesson_03/problem_08.py
students/skowronski_rafal/lesson_02_flow_control/lesson_03/problem_09.py
students/skowronski_rafal/lesson_02_flow_control/lesson_03/problem_10.py
students/skowronski_rafal/lesson_02_flow_control/lesson_03/problem_11.py
students/skowronski_rafal/lesson_02_flow_control/lesson_03/problem_12.py
students/skowronski_rafal/lesson_02_flow_control/lesson_04/problem_06.py
students/skowronski_rafal/lesson_02_flow_control/lesson_04/problem_07.py
students/skowronski_rafal/lesson_02_flow_control/lesson_04/problem_08.py
students/skowronski_rafal/lesson_02_flow_control/lesson_04/problem_09.py
students/skowronski_rafal/lesson_02_flow_control/lesson_04/problem_10.py
students/skowronski_rafal/lesson_02_flow_control/lesson_06/problem_12.py
students/skowronski_rafal/lesson_02_flow_control/lesson_06/problem_13.py

@tomekDiakowTieto Lesson 02 - flow control done

Added lesson 02 - flow control

---

students/skowronski_rafal/.gitignore
students/skowronski_rafal/lesson_03_functions/calculator.py
students/skowronski_rafal/lesson_03_functions/input_validation.py
students/skowronski_rafal/lesson_03_functions/lesson_08/problem_01.py
students/skowronski_rafal/lesson_03_functions/lesson_08/problem_02.py
students/skowronski_rafal/lesson_03_functions/lesson_08/problem_04.py
students/skowronski_rafal/lesson_03_functions/lesson_08/problem_06.py
students/skowronski_rafal/lesson_03_functions/the_collatz_sequence.py

@tomekDiakowTieto lesson 03 is ready

Added: Lesson 03 - functions

---

students/axel_nowaczyk/lesson_03_functions/calculator.py
students/axel_nowaczyk/lesson_03_functions/collatz.py
students/axel_nowaczyk/lesson_03_functions/exponentiation.py
students/axel_nowaczyk/lesson_03_functions/fibonacci_numbers.py
students/axel_nowaczyk/lesson_03_functions/negative_exponent.py
students/axel_nowaczyk/lesson_03_functions/segment_length.py

Tomek diakow tieto/lesson 03 functions

---

students/baker_glenn/lesson_3_scripts/calculator.py
students/baker_glenn/lesson_3_scripts/collatz_sequence.py
students/baker_glenn/lesson_3_scripts/distance.py
students/baker_glenn/lesson_3_scripts/exponentiation_recursion.py
students/baker_glenn/lesson_3_scripts/fibonacci.py
students/baker_glenn/lesson_3_scripts/negative_exponent.py

Scripts for lesson 3

---

students/pietrewicz_bartosz/lesson_03_functions/calculator.py
students/pietrewicz_bartosz/lesson_03_functions/exponentation.py
students/pietrewicz_bartosz/lesson_03_functions/fibonacci_numbers.py
students/pietrewicz_bartosz/lesson_03_functions/input_validation.py
students/pietrewicz_bartosz/lesson_03_functions/negative_exponent.py
students/pietrewicz_bartosz/lesson_03_functions/the_collatz_sequence.py
students/pietrewicz_bartosz/lesson_03_functions/the_length_of_the_segment.py

Solutions for problems from lesson 03

---

students/serek_wojciech/lesson_04_unit_testing/test_collatz.py
students/serek_wojciech/lesson_04_unit_testing/test_distance.py
students/serek_wojciech/lesson_04_unit_testing/test_fib_numbers.py

@gradopaw lesson 04 ready for review

lesson_04_unit_testing: solutions

---

students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson3__last5problems/bishop_moves.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson3__last5problems/chocolate_bar.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson3__last5problems/knight_move.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson3__last5problems/leap_year.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson3__last5problems/queen_move.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson4__last5problems/adding_factorials.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson4__last5problems/factorial.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson4__last5problems/ladder.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson4__last5problems/lost_card.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson4__last5problems/the_number_of_zeros.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson6__2problems/the_number_of_elements_equal_to_the_maximum.py
students/piatkowska_anna/lesson_02_flow_control/Snakify_Lesson6__2problems/the_second_maximum.py

@zamber Ready to review, could you check it?

lesson_02_flow_control

---

students/synowiec_krzysztof/lesson_04_unit_testing/test_fibonacci_numbers.py
students/synowiec_krzysztof/lesson_04_unit_testing/test_the_collatz_sequence.py
students/synowiec_krzysztof/lesson_04_unit_testing/test_the_length_of_the_segment.py

Lesson 4 solutions

---

students/medrek_tomasz/lesson_03_functions/calculator.py
students/medrek_tomasz/lesson_03_functions/exponentation.py
students/medrek_tomasz/lesson_03_functions/fibonacci_numbers.py
students/medrek_tomasz/lesson_03_functions/negative_exponent.py
students/medrek_tomasz/lesson_03_functions/the_collatz_sequence.py
students/medrek_tomasz/lesson_03_functions/the_length_of_the_segment.py

@tomekDiakowTieto , please take a look.
Thanks!
Tomasz

added lesson 3: functions

---

students/bedkowska_julita/lesson_03_functions/Exponentiation.py
students/bedkowska_julita/lesson_03_functions/Fibonacci_numbers.py
students/bedkowska_julita/lesson_03_functions/Negative_exponent.py
students/bedkowska_julita/lesson_03_functions/The_length_of_the_segment.py
students/bedkowska_julita/lesson_03_functions/calculator.py
students/bedkowska_julita/lesson_03_functions/input_validation.py
students/bedkowska_julita/lesson_03_functions/the_collatz_sequence.py

Lesson 03 functions

---

students/olszewski_bartosz/lesson_03_functions/calculator.py
students/olszewski_bartosz/lesson_03_functions/collatz.py
students/olszewski_bartosz/lesson_03_functions/exponentiation.py
students/olszewski_bartosz/lesson_03_functions/fibonacci_numbers.py
students/olszewski_bartosz/lesson_03_functions/negative_exponent.py
students/olszewski_bartosz/lesson_03_functions/the_length_of_the_segment.py

@kamwar please check lesson_03_functions

lesson_03_functions

---

students/kaczmarek_katarzyna/lesson_02_flow_control/adding_factorials.py
students/kaczmarek_katarzyna/lesson_02_flow_control/bishop_moves.py
students/kaczmarek_katarzyna/lesson_02_flow_control/chocolate_bar.py
students/kaczmarek_katarzyna/lesson_02_flow_control/factorial.py
students/kaczmarek_katarzyna/lesson_02_flow_control/knight_move.py
students/kaczmarek_katarzyna/lesson_02_flow_control/ladder.py
students/kaczmarek_katarzyna/lesson_02_flow_control/leap_year.py
students/kaczmarek_katarzyna/lesson_02_flow_control/lost_card.py
students/kaczmarek_katarzyna/lesson_02_flow_control/queen_move.py
students/kaczmarek_katarzyna/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/kaczmarek_katarzyna/lesson_02_flow_control/the_number_of_zeros.py
students/kaczmarek_katarzyna/lesson_02_flow_control/the_second_maximum.py

@kadilak83 - Cześć Marcin! Mam nadzieję, że tym razem się udało. Zerknij proszę czy wszystko jest ok. Pozdrawiam, Kasia.

Lesson 2 - Flow Control - Katarzyna Kaczmarek

---

students/stachowska_agata/lesson_03_functions/calculator.py
students/stachowska_agata/lesson_03_functions/collatz_sequence.py
students/stachowska_agata/lesson_03_functions/fibonacci_rec.py
students/stachowska_agata/lesson_03_functions/length_of_segment.py
students/stachowska_agata/lesson_03_functions/negative_power.py
students/stachowska_agata/lesson_03_functions/power_rec.py

add lesson 03

---

students/grzegorz_bajorski/lesson_03_functions/calculator.py
students/grzegorz_bajorski/lesson_03_functions/exponentiation.py
students/grzegorz_bajorski/lesson_03_functions/fibonacci_numbers.py
students/grzegorz_bajorski/lesson_03_functions/input_validation.py
students/grzegorz_bajorski/lesson_03_functions/negative_exponent.py
students/grzegorz_bajorski/lesson_03_functions/the_collatz_seq.py
students/grzegorz_bajorski/lesson_03_functions/the_length_of_the_segment.py

Signed-off-by: Grzegorz Bajorski <Grzegorz.Bajorski@tieto.com>

Lesson 3 add files

---

students/semko_krzysztof/lesson_04_unit_testing/fibonacci_numbers.py
students/semko_krzysztof/lesson_04_unit_testing/test_collatz.py
students/semko_krzysztof/lesson_04_unit_testing/test_distance.py
students/semko_krzysztof/lesson_04_unit_testing/test_fibonacci_numbers.py
students/semko_krzysztof/lesson_04_unit_testing/the_collatz_sequence.py
students/semko_krzysztof/lesson_04_unit_testing/the_length_of_the_segment.py

lesson_04_unit_testing

---

students/zelichowski_michal/lesson_02_flow_control/adding_factorials.py
students/zelichowski_michal/lesson_02_flow_control/bishop_moves.py
students/zelichowski_michal/lesson_02_flow_control/chocolate_bar.py
students/zelichowski_michal/lesson_02_flow_control/factorial.py
students/zelichowski_michal/lesson_02_flow_control/knight_move.py
students/zelichowski_michal/lesson_02_flow_control/ladder.py
students/zelichowski_michal/lesson_02_flow_control/leap_year.py
students/zelichowski_michal/lesson_02_flow_control/lost_card.py
students/zelichowski_michal/lesson_02_flow_control/queen_move.py
students/zelichowski_michal/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/zelichowski_michal/lesson_02_flow_control/the_number_of_zeroes.py
students/zelichowski_michal/lesson_02_flow_control/the_second_maximum.py

Lesson 02 assignments

---

students/barecki_andrzej/lesson_03_functions/L3_Collatz_Sequence.py
students/barecki_andrzej/lesson_03_functions/L3_Exponentiation.py
students/barecki_andrzej/lesson_03_functions/L3_Fibonacci_numbers.py
students/barecki_andrzej/lesson_03_functions/L3_Negative_exponent.py
students/barecki_andrzej/lesson_03_functions/L3_The_length_of_the_segment.py
students/barecki_andrzej/lesson_03_functions/L3_calculator.py

jedzej/lesson_03_function: initial version

---

students/surowiec_marek/lesson_03_funcions/calculator.py
students/surowiec_marek/lesson_03_funcions/exponentiation.py
students/surowiec_marek/lesson_03_funcions/fibonacci_numbers.py
students/surowiec_marek/lesson_03_funcions/input_validation.py
students/surowiec_marek/lesson_03_funcions/negative_exponent.py
students/surowiec_marek/lesson_03_funcions/the_collatz_sequence.py
students/surowiec_marek/lesson_03_funcions/the_length_of_the_segment.py

Lesson 03 completed

---

students/swietczak_monika/lesson_04_unit_testing/test_Fibonacci.py
students/swietczak_monika/lesson_04_unit_testing/test_collatz.py
students/swietczak_monika/lesson_04_unit_testing/test_distance.py

Added lesson 04 solutions again

---

students/ryba_paula/lesson_04_unit_tests/fibonacci_numbers.py
students/ryba_paula/lesson_04_unit_tests/test_collatz.py
students/ryba_paula/lesson_04_unit_tests/test_distance.py
students/ryba_paula/lesson_04_unit_tests/test_fibonacci.py
students/ryba_paula/lesson_04_unit_tests/the_collatz_sequence_and_validation.py
students/ryba_paula/lesson_04_unit_tests/the_length_of_the_segment.py

@kadilak83 proszę o sprawdzenie

Add lesson_04_unit_testing solutions

---

students/kaczmarek_katarzyna/lesson_03_functions/calculator.py
students/kaczmarek_katarzyna/lesson_03_functions/collatz_sequence_with_validation.py
students/kaczmarek_katarzyna/lesson_03_functions/exponentiation.py
students/kaczmarek_katarzyna/lesson_03_functions/fibonacci_numbers.py
students/kaczmarek_katarzyna/lesson_03_functions/negative_exponent.py
students/kaczmarek_katarzyna/lesson_03_functions/the_length_of_the_segment.py

@kadilak83 Cześć Marcin. Rzuć proszę okiem na zadanka z lekcji 3. Powoli nadrabiam zaległości...

Lesson 3 - All issues

---

students/kaczmarek_katarzyna/lesson_04_unit_testing/collatz_sequence_with_validation.py
students/kaczmarek_katarzyna/lesson_04_unit_testing/fibonacci_numbers.py
students/kaczmarek_katarzyna/lesson_04_unit_testing/test_collatz.py
students/kaczmarek_katarzyna/lesson_04_unit_testing/test_distance.py
students/kaczmarek_katarzyna/lesson_04_unit_testing/test_fibonacci_numbers.py
students/kaczmarek_katarzyna/lesson_04_unit_testing/the_length_of_the_segment.py

@kadilak83 Cześć Marcin. Zerknij proszę na moje testy jednostkowe. Pozdrawiam, Kasia.

Lesson 4 - Tests

---

students/piatkowska_anna/lesson_04_unit_testing/01/collatz.py
students/piatkowska_anna/lesson_04_unit_testing/01/unit_tests_collatz.py
students/piatkowska_anna/lesson_04_unit_testing/02/length_of_the_segment.py
students/piatkowska_anna/lesson_04_unit_testing/02/unittest_distance.py
students/piatkowska_anna/lesson_04_unit_testing/03/fibonacci_numbers.py
students/piatkowska_anna/lesson_04_unit_testing/03/test_fibonacci.py

@zamber Ready to review, could you check it?

lesson 04 unit testing

---

students/adam_wulw/lesson_03_functions/calculator.py
students/adam_wulw/lesson_03_functions/calculator.py~
students/adam_wulw/lesson_03_functions/exponentiation.py
students/adam_wulw/lesson_03_functions/fibonacci_numbers.py
students/adam_wulw/lesson_03_functions/fibonacci_numbers.py~
students/adam_wulw/lesson_03_functions/negative_exponent.py
students/adam_wulw/lesson_03_functions/the_collatz_sequence.py
students/adam_wulw/lesson_03_functions/the_collatz_sequence.py~
students/adam_wulw/lesson_03_functions/the_length_of_segment.py
students/adam_wulw/lesson_03_functions/the_length_of_segment.py~

All lesson 3

---

students/medrek_tomasz/lesson_04_unit_testing/collatz_unit_tests.py
students/medrek_tomasz/lesson_04_unit_testing/distance_unit_tests.py
students/medrek_tomasz/lesson_04_unit_testing/fibonacci_numbers.py
students/medrek_tomasz/lesson_04_unit_testing/fibonacci_unit_tests.py
students/medrek_tomasz/lesson_04_unit_testing/the_collatz_sequence.py
students/medrek_tomasz/lesson_04_unit_testing/the_length_of_the_segment.py

@tomekDiakowTieto , please take a look.
Thanks!
Tomasz

added lesson 04: unit testing

---

students/bedkowska_julita/lesson_04_unit_testing/test_Fibonacci.py
students/bedkowska_julita/lesson_04_unit_testing/test_collatz.py
students/bedkowska_julita/lesson_04_unit_testing/test_distance.py

Lesson 4 - Unit tests

---

students/adam_wulw/lesson_03_functions/calculator.py
students/adam_wulw/lesson_03_functions/calculator.py~
students/adam_wulw/lesson_03_functions/exponentiation.py
students/adam_wulw/lesson_03_functions/fibonacci_numbers.py
students/adam_wulw/lesson_03_functions/fibonacci_numbers.py~
students/adam_wulw/lesson_03_functions/negative_exponent.py
students/adam_wulw/lesson_03_functions/the_collatz_sequence.py
students/adam_wulw/lesson_03_functions/the_collatz_sequence.py~
students/adam_wulw/lesson_03_functions/the_length_of_segment.py
students/adam_wulw/lesson_03_functions/the_length_of_segment.py~
students/adam_wulw/lesson_04_unit_testing/test_collatz.py
students/adam_wulw/lesson_04_unit_testing/test_fib_num.py
students/adam_wulw/lesson_04_unit_testing/test_pytest_distance.py

Tomek diakow tieto/lesson 04 unit testing

---

students/saleta_sebastian/lesson_03_functions/collatz.py

@gradopaw I did the collatz application but I focus on fixing other apps and I didn't check untracked files.

Add missing collatz application

---

students/hyska_monika/lesson_03_functions/Exponentiation
students/hyska_monika/lesson_03_functions/FibonacciNumbers
students/hyska_monika/lesson_03_functions/NegativeExponen2
students/hyska_monika/lesson_03_functions/NegativeExponent
students/hyska_monika/lesson_03_functions/TheLengthOfTheSegment
students/hyska_monika/lesson_03_functions/calculator_refactoring

Hyska_Monika_lesson_04

---

students/biegon_piotr/lesson_04_unit_testing/distance_of_the_segment.py
students/biegon_piotr/lesson_04_unit_testing/fibonacci.py
students/biegon_piotr/lesson_04_unit_testing/test_distance.py
students/biegon_piotr/lesson_04_unit_testing/test_fibonacci.py
students/biegon_piotr/lesson_04_unit_testing/unitests_collatz.py

Lesson 4 - Unit testing

---

students/kosarzewski_maciej/lesson_04_unit_testing/collatz/collatz_sequence.py
students/kosarzewski_maciej/lesson_04_unit_testing/collatz/collatz_unittest.py
students/kosarzewski_maciej/lesson_04_unit_testing/fibonacci/fibonacci_number.py
students/kosarzewski_maciej/lesson_04_unit_testing/fibonacci/fibonacci_unittest.py
students/kosarzewski_maciej/lesson_04_unit_testing/segment_lenght/lenght_of_segment.py
students/kosarzewski_maciej/lesson_04_unit_testing/segment_lenght/lenght_unittest.py

Lesson 04: unit testing

---

students/saleta_sebastian/lesson_04_unit_testing/test_collatz.py
students/saleta_sebastian/lesson_04_unit_testing/test_fib.py
students/saleta_sebastian/lesson_04_unit_testing/test_the_length_of_the_segment.py

Results of lesson_04.

---

students/medrek_tomasz/lesson_05_lists/age_calculator.py
students/medrek_tomasz/lesson_05_lists/character_picture_grid.py
students/medrek_tomasz/lesson_05_lists/chess_board.py
students/medrek_tomasz/lesson_05_lists/comma_code.py
students/medrek_tomasz/lesson_05_lists/greater_than_neighbours.py
students/medrek_tomasz/lesson_05_lists/maximum.py
students/medrek_tomasz/lesson_05_lists/numbers_filter.py
students/medrek_tomasz/lesson_05_lists/swap_min_and_max.py
students/medrek_tomasz/lesson_05_lists/the_bowling_alley.py
students/medrek_tomasz/lesson_05_lists/the_diagonal_parallel_to_the_main.py
students/medrek_tomasz/lesson_05_lists/unit_tests_age_calculator.py
students/medrek_tomasz/lesson_05_lists/unit_tests_character_picture_grid.py
students/medrek_tomasz/lesson_05_lists/unit_tests_comma_code.py
students/medrek_tomasz/lesson_05_lists/unit_tests_numbers_filter.py

@tomekDiakowTieto: please take a look.
Thanks,
Tomasz

added lesson 05: lists

---

.gitignore

Hi @jedzej 
Please consider merging this.
Thanks,
Tomasz

git: ignore pytest caches

---

students/jakielczyk_miroslaw/lesson_05_lists/age_calculator.py
students/jakielczyk_miroslaw/lesson_05_lists/character_picture_grid.py
students/jakielczyk_miroslaw/lesson_05_lists/chess_board.py
students/jakielczyk_miroslaw/lesson_05_lists/comma_code.py
students/jakielczyk_miroslaw/lesson_05_lists/greater_than_neighbours.py
students/jakielczyk_miroslaw/lesson_05_lists/maximum.py
students/jakielczyk_miroslaw/lesson_05_lists/numbers_filter.py
students/jakielczyk_miroslaw/lesson_05_lists/swap_min_and_max.py
students/jakielczyk_miroslaw/lesson_05_lists/swap_the_columns.py
students/jakielczyk_miroslaw/lesson_05_lists/the_bowling_alley.py
students/jakielczyk_miroslaw/lesson_05_lists/the_diagonal_parallel_to_the_main.py

added tasks for lesson_05_lists

---

students/ryba_paula/lesson_05_lists/age_calculator.py
students/ryba_paula/lesson_05_lists/character_picture_grid.py
students/ryba_paula/lesson_05_lists/chess_board.py
students/ryba_paula/lesson_05_lists/comma_code.py
students/ryba_paula/lesson_05_lists/greater_than_neighbours.py
students/ryba_paula/lesson_05_lists/maximum.py
students/ryba_paula/lesson_05_lists/numbers_filter.py
students/ryba_paula/lesson_05_lists/swap_min_and_max.py
students/ryba_paula/lesson_05_lists/swap_the_columns.py
students/ryba_paula/lesson_05_lists/the_bowling_alley.py
students/ryba_paula/lesson_05_lists/the_diagonal_parallel_to_the_main.py

Add lesson_05_lists solutions

---

students/semko_krzysztof/lesson_05_lists/age_calculator.py
students/semko_krzysztof/lesson_05_lists/character_picture_grid.py
students/semko_krzysztof/lesson_05_lists/chess_board.py
students/semko_krzysztof/lesson_05_lists/comma_code.py
students/semko_krzysztof/lesson_05_lists/greater_than_neighbours.py
students/semko_krzysztof/lesson_05_lists/maximum.py
students/semko_krzysztof/lesson_05_lists/numbers_filter.py
students/semko_krzysztof/lesson_05_lists/swap_min_max.py
students/semko_krzysztof/lesson_05_lists/the_bowling_alley.py
students/semko_krzysztof/lesson_05_lists/the_diagonal_parallel_to_the_main.py

Work in progress.
This will be updated.

semko_krzysztof/lesson_05_lists

---

students/burko_szymon/lesson_02_flow_control/README.md
students/burko_szymon/lesson_02_flow_control/adding_factorials.py
students/burko_szymon/lesson_02_flow_control/bishop_moves.py
students/burko_szymon/lesson_02_flow_control/chocolate_bar.py
students/burko_szymon/lesson_02_flow_control/factorial.py
students/burko_szymon/lesson_02_flow_control/knight_move.py
students/burko_szymon/lesson_02_flow_control/ladder.py
students/burko_szymon/lesson_02_flow_control/leap_year.py
students/burko_szymon/lesson_02_flow_control/lost_card.py
students/burko_szymon/lesson_02_flow_control/queen_move.py
students/burko_szymon/lesson_02_flow_control/the_number_of_elements_equal_to_the_maximum.py
students/burko_szymon/lesson_02_flow_control/the_number_of_zeroes.py
students/burko_szymon/lesson_02_flow_control/the_second_maximum.py

Lesson 02 added

---

students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/args.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words.py
students/mielczarek_szymon/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@kuszcjan: done, please review

Lesson 06: Add solutions for all projects

---

students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words_in_some_text.py
students/jakielczyk_miroslaw/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@kuszcjan, please make a review

added tasks for lesson_06_dicts_tuples_sets_args_kwargs

---

students/slupek_bartosz/lesson_03_functions/Calculator.py
students/slupek_bartosz/lesson_03_functions/collatz.py
students/slupek_bartosz/lesson_03_functions/exponentiation.py
students/slupek_bartosz/lesson_03_functions/fibonacci_numbers.py
students/slupek_bartosz/lesson_03_functions/negative_exponent.py
students/slupek_bartosz/lesson_03_functions/the_length_of_the_segment.py

Add lesson 3

---

students/mielczarek_szymon/lesson07_string_datetime/data_printer.py
students/mielczarek_szymon/lesson07_string_datetime/date_calculator.py
students/mielczarek_szymon/lesson07_string_datetime/delta_time_calculator.py
students/mielczarek_szymon/lesson07_string_datetime/strings.py
students/mielczarek_szymon/lesson07_string_datetime/table_printer.py
students/mielczarek_szymon/lesson07_string_datetime/timestamp_to_date.py

@kuszcjan: done, please review

Add solutions for lesson_07

---

students/jemielity_kamil/lesson_05_lists/README.md
students/jemielity_kamil/lesson_05_lists/age_calculator.py
students/jemielity_kamil/lesson_05_lists/character_picture_grid.py
students/jemielity_kamil/lesson_05_lists/chess_board.py
students/jemielity_kamil/lesson_05_lists/comma_code.py
students/jemielity_kamil/lesson_05_lists/greater_than_neighbours.py
students/jemielity_kamil/lesson_05_lists/maximum.py
students/jemielity_kamil/lesson_05_lists/numbers_filter.py
students/jemielity_kamil/lesson_05_lists/swap_min_and_max.py
students/jemielity_kamil/lesson_05_lists/swap_the_columns.py
students/jemielity_kamil/lesson_05_lists/the_bowling_alley.py
students/jemielity_kamil/lesson_05_lists/the_diagonal_parallel_to_the_main.py

Lesson 05 lists

---

students/olszewski_bartosz/lesson_04_unit_testing/.pytest_cache/v/cache/nodeids
students/olszewski_bartosz/lesson_04_unit_testing/collatz_test.py
students/olszewski_bartosz/lesson_04_unit_testing/distance_test.py
students/olszewski_bartosz/lesson_04_unit_testing/fibonacci_test.py

@kamwar lesson04_unit_testing please check

lesson04_unit_testing

---

students/synowiec_krzysztof/lesson_07_string_datetime/date_calculator.py
students/synowiec_krzysztof/lesson_07_string_datetime/date_printer.py
students/synowiec_krzysztof/lesson_07_string_datetime/delete_a_character.py
students/synowiec_krzysztof/lesson_07_string_datetime/delete_every_third_character.py
students/synowiec_krzysztof/lesson_07_string_datetime/delta_time_calculator.py
students/synowiec_krzysztof/lesson_07_string_datetime/remove_the_fragment.py
students/synowiec_krzysztof/lesson_07_string_datetime/replace_the_substring.py
students/synowiec_krzysztof/lesson_07_string_datetime/replace_within_the_fragment.py
students/synowiec_krzysztof/lesson_07_string_datetime/reverse_the_fragment.py
students/synowiec_krzysztof/lesson_07_string_datetime/table_printer.py
students/synowiec_krzysztof/lesson_07_string_datetime/the_first_and_last_occurrence.py
students/synowiec_krzysztof/lesson_07_string_datetime/the_number_of_words.py
students/synowiec_krzysztof/lesson_07_string_datetime/the_second_occurrence.py
students/synowiec_krzysztof/lesson_07_string_datetime/the_two_halves.py
students/synowiec_krzysztof/lesson_07_string_datetime/timestamp_to_date.py
students/synowiec_krzysztof/lesson_07_string_datetime/to_swap_the_two_words.py

Lesson 7 solutions

---

students/arkadiusz_kasprzyk/lesson_04_unit_testing/test_collatz.py
students/arkadiusz_kasprzyk/lesson_04_unit_testing/test_distance.py
students/arkadiusz_kasprzyk/lesson_04_unit_testing/test_fibonacci.py

create branch adziu/lesson_04_unit_testing

---

students/sendecki_andrzej/lesson_02_flow_control/lesson3-bishop_moves.py
students/sendecki_andrzej/lesson_02_flow_control/lesson3-chocolate_bar.py
students/sendecki_andrzej/lesson_02_flow_control/lesson3-knight_move.py
students/sendecki_andrzej/lesson_02_flow_control/lesson3-leap_year.py
students/sendecki_andrzej/lesson_02_flow_control/lesson3-minimum_of_two_numbers.py
students/sendecki_andrzej/lesson_02_flow_control/lesson3-queen_move.py
students/sendecki_andrzej/lesson_02_flow_control/lesson4-adding_factorials.py
students/sendecki_andrzej/lesson_02_flow_control/lesson4-factorial.py
students/sendecki_andrzej/lesson_02_flow_control/lesson4-ladder.py
students/sendecki_andrzej/lesson_02_flow_control/lesson4-lost_card.py
students/sendecki_andrzej/lesson_02_flow_control/lesson4-the_number_of_zeros.py
students/sendecki_andrzej/lesson_02_flow_control/lesson6-the_number_of_elements_equal_to_the_maximum.py
students/sendecki_andrzej/lesson_02_flow_control/lesson6-the_second_maximum.py

@kuszcjan 
Please check my commits for lesson02 - Flow Control.

lesson_02_flow_control problems

---

students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/distinct_words.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/guess_number.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/list_to_dictionary_fantasy_game.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/rest_functions.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/lakatorz_izaak/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@jedzej Częściowe rozwiązania, reszte wyśle do końca tygodnia.

jedzej/Lesson 06 (partial work)

---

students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words_in_some_text.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/unit_tests_args_sum.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

Hi @tomekDiakowTieto 
Thanks,
Tomasz

added lesson 6 - dictionaries, tuples and sets

---

lesson_03-4.py
lesson_03-5.py
lesson_03-6.py
students/halas_maciek/lesson_01/lesson_03-2.py
students/halas_maciek/lesson_01/lesson_03-3.py
students/halas_maciek/lesson_01/lesson_03_functions.py

'lesson_03'

---

students/sendecki_andrzej/lesson_03_functions/calculator.py
students/sendecki_andrzej/lesson_03_functions/lesson8-exponentiation.py
students/sendecki_andrzej/lesson_03_functions/lesson8-fibonnachi_numbers.py
students/sendecki_andrzej/lesson_03_functions/lesson8-negative_exponent.py
students/sendecki_andrzej/lesson_03_functions/lesson8-the_length_of_the_segment.py
students/sendecki_andrzej/lesson_03_functions/the_collatz_sequence.py
students/sendecki_andrzej/lesson_03_functions/the_collatz_sequence_exceptions.py

@kuszcjan 
Please check the lesson03 exercises.

Add lesson_03_functions exercises

---

students/sendecki_andrzej/lesson_04_unit_testing/test_lesson8-fibonnacci_numbers.py
students/sendecki_andrzej/lesson_04_unit_testing/test_lesson8-the_length_of_the_segment.py
students/sendecki_andrzej/lesson_04_unit_testing/the_collatz_unittest.py

@kuszcjan 
Please check my exercises of lesson 04 -unit testing

lesson_04_unit_testing exercises

---

students/jakielczyk_miroslaw/lesson_07_string_datetime/date_calculator.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/date_printer.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/delta_time_calculator.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/replace_the_substring.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/table_printer.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/the_number_of_words.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/timestamp_to_date.py
students/jakielczyk_miroslaw/lesson_07_string_datetime/to_swap_the_two_words.py

tasks for lesson_07_string_datetime

---

students/hyska_monika/lesson_02_flow_control/AddinFactorials.py
students/hyska_monika/lesson_02_flow_control/BishopMoves.py
students/hyska_monika/lesson_02_flow_control/ChoocolateBar.py
students/hyska_monika/lesson_02_flow_control/Factorial.py
students/hyska_monika/lesson_02_flow_control/KnightMove.py
students/hyska_monika/lesson_02_flow_control/Ladder.py
students/hyska_monika/lesson_02_flow_control/LeapYear.py
students/hyska_monika/lesson_02_flow_control/LostCar.py
students/hyska_monika/lesson_02_flow_control/QueenMove.py
students/hyska_monika/lesson_02_flow_control/TheNumberOfElementsEqualToTheMaximum.py
students/hyska_monika/lesson_02_flow_control/TheNumbersOfZeros.py
students/hyska_monika/lesson_02_flow_control/TheSecondMaximum.py

Hyska_lesson2

---

students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/list_fantasy_game_inventory.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words.py
students/ryba_paula/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@kadilak83 proszę o review (wreszcie ;))
W zadaniach z inputem użytkownika pominęłam opisywanie inputu (np. "Please give a number") - nie chciałam tracić na to czasu, a wiesz, że to umiem.
Zadanie 'Uppercase' - zakładam, że funkcji title() nie można było użyć?
Zadanie 'Logger wrapper' - nie wiem, czy dobrze je zrozumiałam.

Add lesson_06

---

students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/list_to_fictionary_function_for_fantasy_game_inventory.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words_in_some_text.py
students/kaczmarek_katarzyna/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@kadilak83 Cześć Marcin! Zerknij proszę na zadania z lekcji 6. Pozdrawiam, Kasia!

Lesson 6 - All issues

---

students/synowiec_krzysztof/lesson_08_regular_expressions/email_validator.py
students/synowiec_krzysztof/lesson_08_regular_expressions/phone_number_validator.py
students/synowiec_krzysztof/lesson_08_regular_expressions/postal_code_validator.py
students/synowiec_krzysztof/lesson_08_regular_expressions/regex_version_of_strip.py
students/synowiec_krzysztof/lesson_08_regular_expressions/strong_password_detection.py

Lesson 8 solutions

---

students/ryba_paula/lesson_07_string_datetime/date_calculator.py
students/ryba_paula/lesson_07_string_datetime/date_printer.py
students/ryba_paula/lesson_07_string_datetime/delta_time_calculator.py
students/ryba_paula/lesson_07_string_datetime/replace_the_substring.py
students/ryba_paula/lesson_07_string_datetime/table_printer.py
students/ryba_paula/lesson_07_string_datetime/the_number_of_words.py
students/ryba_paula/lesson_07_string_datetime/timestamp_to_date.py
students/ryba_paula/lesson_07_string_datetime/to_swap_the_two_words.py

Add lesson_07

---

students/semko_krzysztof/lesson_06_dictionaries/access_rights.py
students/semko_krzysztof/lesson_06_dictionaries/args_inspector.py
students/semko_krzysztof/lesson_06_dictionaries/args_sum.py
students/semko_krzysztof/lesson_06_dictionaries/countries_and_cities.py
students/semko_krzysztof/lesson_06_dictionaries/cubes.py
students/semko_krzysztof/lesson_06_dictionaries/fantasy_game_inventory.py
students/semko_krzysztof/lesson_06_dictionaries/frequency_analysis.py
students/semko_krzysztof/lesson_06_dictionaries/guess_the_number.py
students/semko_krzysztof/lesson_06_dictionaries/list_to_dictionary_f_for_fantasy_game_inventory.py
students/semko_krzysztof/lesson_06_dictionaries/logger_wrapper.py
students/semko_krzysztof/lesson_06_dictionaries/reverse_the_sequence.py
students/semko_krzysztof/lesson_06_dictionaries/the_number_of_distinct_words.py
students/semko_krzysztof/lesson_06_dictionaries/uppercase.py

@jedzej
lesson_06 sets, dictionaries, tuples

lesson_06_dictionaries

---

students/urtnowski_daniel/lesson_06_dicts_tuples_sets_args_kwargs/args_and_kwargs.py
students/urtnowski_daniel/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game.py
students/urtnowski_daniel/lesson_06_dicts_tuples_sets_args_kwargs/snakify_lesson_10.py
students/urtnowski_daniel/lesson_06_dicts_tuples_sets_args_kwargs/snakify_lesson_11.py
students/urtnowski_daniel/lesson_06_dicts_tuples_sets_args_kwargs/snakify_lesson_8.py

@jedzej Lesson 6 finished, please review

Adding solutions for Lesson 6: Dictionaries, tuples etc

---

students/urtnowski_daniel/lesson_07_strings_and_datetime/datetime_projects.py
students/urtnowski_daniel/lesson_07_strings_and_datetime/snakify_lesson_5.py
students/urtnowski_daniel/lesson_07_strings_and_datetime/table_printer.py

@jedzej Lekcja 7 gotowa, proszę o review

Adding solutions for Lesson 7: Manipulating strings + datetime formatting

---

students/semko_krzysztof/lesson_07_strings_manipulation/date_calculator.py
students/semko_krzysztof/lesson_07_strings_manipulation/date_printer.py
students/semko_krzysztof/lesson_07_strings_manipulation/delta_time_calculator.py
students/semko_krzysztof/lesson_07_strings_manipulation/replace_the_substring.py
students/semko_krzysztof/lesson_07_strings_manipulation/table_printer.py
students/semko_krzysztof/lesson_07_strings_manipulation/the_number_of_words.py
students/semko_krzysztof/lesson_07_strings_manipulation/timestamp_to_date.py
students/semko_krzysztof/lesson_07_strings_manipulation/to_swap_the_two_words.py

@jedzej
lesson 07 strings and datetime

lesson_07_strings_manipulation

---

students/jemielity_kamil/lesson_07_string_datetime/date_calculator.py
students/jemielity_kamil/lesson_07_string_datetime/date_printer.py
students/jemielity_kamil/lesson_07_string_datetime/delta_time_calculator.py
students/jemielity_kamil/lesson_07_string_datetime/replace_the_substring.py
students/jemielity_kamil/lesson_07_string_datetime/table_printer.py
students/jemielity_kamil/lesson_07_string_datetime/the_number_of_words.py
students/jemielity_kamil/lesson_07_string_datetime/timestamp_to_date.py
students/jemielity_kamil/lesson_07_string_datetime/to_swap_the_two_words.py

lesson 07 manipulating strings + datetime formatting tasks

---

students/mielczarek_szymon/lesson_09_reading_and_writing_files/input_file.txt
students/mielczarek_szymon/lesson_09_reading_and_writing_files/mad_libs.py
students/mielczarek_szymon/lesson_09_reading_and_writing_files/mcb.pyw
students/mielczarek_szymon/lesson_09_reading_and_writing_files/regex_search.py

Add solutions for lesson_09

---

students/kondel_tomasz/lesson_03_funtions/fibonacci_numbers.py
students/kondel_tomasz/lesson_03_funtions/the_collatz_sequence.py
students/kondel_tomasz/lesson_03_funtions/the_length_of_the_segment.py
students/kondel_tomasz/lesson_04_unit_testing/collatz_test.py
students/kondel_tomasz/lesson_04_unit_testing/distance_test.py
students/kondel_tomasz/lesson_04_unit_testing/fibonacci_test.py

@adziu,  I've modified and added 3 files from Lesson 3 because these files haven't been merged.

Lesson 4: unit tests and functions from L3.

---

students/kaczmarek_katarzyna/lesson_07_string_datetime/date_calculator.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/date_printer.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/delta_time_calculator.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/replace_the_substring.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/table_printer.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/the_number_of_words.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/timestamp_to_date.py
students/kaczmarek_katarzyna/lesson_07_string_datetime/to_swap_the_two_words.py

@kadilak83 Cześć Marcin. Przesyłam lekcję numer 7. Pozdrawiam, Kasia :)

Lesson 07 - All issues

---

students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words_in_some_text.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

Result of lesson 06.

---

students/mielczarek_szymon/lesson_10_organizing_files/deleting_unneeded_files.py
students/mielczarek_szymon/lesson_10_organizing_files/filling_in_the_gaps.py
students/mielczarek_szymon/lesson_10_organizing_files/selective_copy.py

@kuszcjan: ready, please review

Add solutions for lesson_10

---

students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/saleta_sebastian/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@gradopaw I preferred to make your corrections. My problem with parenthesis is from Java

Last corrections of lesson06.

---

students/piechowski_michal/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
students/piechowski_michal/lesson_09_reading_and_writing_files/mad_libs.py
students/piechowski_michal/lesson_09_reading_and_writing_files/mad_libs_text.txt
students/piechowski_michal/lesson_09_reading_and_writing_files/regex_search.py

Add lesson_09 exercises

---

students/medrek_tomasz/lesson_08_regular_expressions/email_validator.py
students/medrek_tomasz/lesson_08_regular_expressions/phone_number_validator.py
students/medrek_tomasz/lesson_08_regular_expressions/postal_code_validator_poland.py
students/medrek_tomasz/lesson_08_regular_expressions/regex_version_of_strip.py
students/medrek_tomasz/lesson_08_regular_expressions/strong_password_detection.py
students/medrek_tomasz/lesson_08_regular_expressions/unit_tests_email_validator.py
students/medrek_tomasz/lesson_08_regular_expressions/unit_tests_phone_number_validator.py
students/medrek_tomasz/lesson_08_regular_expressions/unit_tests_regex_version_of_strip.py
students/medrek_tomasz/lesson_08_regular_expressions/unit_tests_strong_password_detection.py

Dear @tomekDiakowTieto 
Please take a look,
Thanks,
Tomasz

added lesson 08: regular expressions

---

students/medrek_tomasz/lesson_04_unit_testing/distance_unit_tests.py
students/medrek_tomasz/lesson_04_unit_testing/fibonacci_unit_tests.py
students/medrek_tomasz/lesson_05_lists/comma_code.py
students/medrek_tomasz/lesson_05_lists/unit_tests_age_calculator.py
students/medrek_tomasz/lesson_05_lists/unit_tests_character_picture_grid.py
students/medrek_tomasz/lesson_05_lists/unit_tests_comma_code.py
students/medrek_tomasz/lesson_05_lists/unit_tests_numbers_filter.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/medrek_tomasz/lesson_06_dicts_tuples_sets_args_kwargs/unit_tests_args_sum.py

Dear @tomekDiakowTieto 
Please take a look:
I fixed things according to your comments and unit tests code which I strongly didn't like, but didn't know how to make them better before.
Thanks,
Tomasz

fix already merged lessons: 04, 05 and 06

---

students/medrek_tomasz/lesson_07_string_datetime/date_calculator.py
students/medrek_tomasz/lesson_07_string_datetime/date_printer.py
students/medrek_tomasz/lesson_07_string_datetime/delta_time_calculator.py
students/medrek_tomasz/lesson_07_string_datetime/replace_the_substring.py
students/medrek_tomasz/lesson_07_string_datetime/table_printer.py
students/medrek_tomasz/lesson_07_string_datetime/the_number_of_words.py
students/medrek_tomasz/lesson_07_string_datetime/timestamp_to_date.py
students/medrek_tomasz/lesson_07_string_datetime/to_swap_the_two_words.py
students/medrek_tomasz/lesson_07_string_datetime/unit_tests_date_calculator.py
students/medrek_tomasz/lesson_07_string_datetime/unit_tests_table_printer.py

Dear @tomekDiakowTieto 
Thanks!
Tomasz

added lesson 07 - manipulating strings + datetime

---

students/skowronski_rafal/lesson_07_string_datetime/project_01_table_printer/table_printer.py
students/skowronski_rafal/lesson_07_string_datetime/project_01_table_printer/test_table_printer.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/replace_the_substring.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/test_replace_the_substring.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/test_the_number_of_words.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/test_to_swap_the_two_words.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/the_number_of_words.py
students/skowronski_rafal/lesson_07_string_datetime/project_02_snakify_lesson_05/to_swap_the_two_words.py
students/skowronski_rafal/lesson_07_string_datetime/project_03_04_05_06_date_time/date_time.py
students/skowronski_rafal/lesson_07_string_datetime/project_03_04_05_06_date_time/test_date_time.py

@tomekDiakowTieto: Lesson 07 ready

Add Lesson 07: string and datetime

---

students/skowronski_rafal/lesson_08_regular_expressions/regex.py
students/skowronski_rafal/lesson_08_regular_expressions/test_regex.py

@tomekDiakowTieto Finally added Lesson 8 - regular expressions

Add Lesson 8 - Regular expressions

---

students/adam_wulw/lesson_06_dictionaries/access_right.py
students/adam_wulw/lesson_06_dictionaries/countries_and_cities.py
students/adam_wulw/lesson_06_dictionaries/frequency_analysis.py
students/adam_wulw/lesson_06_dictionaries/guess_the_number.py
students/adam_wulw/lesson_06_dictionaries/inventory.py
students/adam_wulw/lesson_06_dictionaries/inventory_add.py
students/adam_wulw/lesson_06_dictionaries/reverse.py
students/adam_wulw/lesson_06_dictionaries/sum_inspector_wrapper.py
students/adam_wulw/lesson_06_dictionaries/the_number_of_distinct_word_in_some_text.py
students/adam_wulw/lesson_06_dictionaries/uppercase.py

All lesson 6

---

students/adam_wulw/lesson_07_manipulating_strings/data_calculator.py
students/adam_wulw/lesson_07_manipulating_strings/date_printer.py
students/adam_wulw/lesson_07_manipulating_strings/delta_time_calculator.py
students/adam_wulw/lesson_07_manipulating_strings/replace_the_substring.py
students/adam_wulw/lesson_07_manipulating_strings/table_printer.py
students/adam_wulw/lesson_07_manipulating_strings/the_number_of_words.py
students/adam_wulw/lesson_07_manipulating_strings/timestamp_to_date.py
students/adam_wulw/lesson_07_manipulating_strings/to_swap_the_two_words.py

All lesson 7

---

students/semko_krzysztof/lesson_08_regular_expressions/email_validator.py
students/semko_krzysztof/lesson_08_regular_expressions/phone_number_validator.py
students/semko_krzysztof/lesson_08_regular_expressions/postal_code_validator.py
students/semko_krzysztof/lesson_08_regular_expressions/regex_version_of_strip.py
students/semko_krzysztof/lesson_08_regular_expressions/strong_password_detection.py

@jedzej
Initial lesson_08 regex

semko_krzysztof/lesson_08_regular_expressions

---

students/urtnowski_daniel/lesson_08_regular_expressions/automate_the_boring_stuff.py
students/urtnowski_daniel/lesson_08_regular_expressions/regex_validators.py

@jedzej  Lekcja 8 gotowa, proszę o review

Adding solutions for Lesson 8: Regular expressions

---

students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/guess_the_number.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/inventory.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/list_to_dictionary.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/the_number_of_distinct_words.py
students/swietczak_monika/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

Added lesson_06 solutions

---

students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/access_rights.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/args_inspector.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/args_sum.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/countries_and_cities.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/cubes.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/frequency_analysis.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/guess_number.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/list_to_dictionary_fantasy_game.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/number_of_unique.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/reverse_the_sequence.py
students/stachowska_agata/lesson_06_dicts_tuples_sets_args_kwargs/uppercase.py

@kamwar  lesson06 ready to check

added lesson 06

---

students/swietczak_monika/lesson_07_string_datetime/date_calculator.py
students/swietczak_monika/lesson_07_string_datetime/date_printer.py
students/swietczak_monika/lesson_07_string_datetime/delta_time_calculator.py
students/swietczak_monika/lesson_07_string_datetime/replace_the_substring.py
students/swietczak_monika/lesson_07_string_datetime/table_printer.py
students/swietczak_monika/lesson_07_string_datetime/the_number_of_words.py
students/swietczak_monika/lesson_07_string_datetime/timestamp_to_date.py
students/swietczak_monika/lesson_07_string_datetime/to_swap_the_two_words.py

Added lesson 07 solutions

---

students/saleta_sebastian/lesson_07_string_datetime/date_calculator.py
students/saleta_sebastian/lesson_07_string_datetime/date_printer.py
students/saleta_sebastian/lesson_07_string_datetime/delta_time_calculator.py
students/saleta_sebastian/lesson_07_string_datetime/replace_the_substring.py
students/saleta_sebastian/lesson_07_string_datetime/table_printer.py
students/saleta_sebastian/lesson_07_string_datetime/the_number_of_words.py
students/saleta_sebastian/lesson_07_string_datetime/time_stamp_to_date.py
students/saleta_sebastian/lesson_07_string_datetime/to_swap_the_two_words.py

Result of 07 lessons

---

students/kaczmarek_katarzyna/lesson_10_organizing_files/deleting_unneeded_files.py
students/kaczmarek_katarzyna/lesson_10_organizing_files/filling_in_the_gaps.py
students/kaczmarek_katarzyna/lesson_10_organizing_files/selective_copy.py

@kadilak83 - Hej Marcin. Zerknij proszę na lekcję 10 czy wszystko jest ok. Pozdrawiam, Kasia.

Lesson 10 - All tasks

---

students/ryba_paula/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
students/ryba_paula/lesson_09_reading_and_writing_files/file.txt
students/ryba_paula/lesson_09_reading_and_writing_files/mad_libs.py
students/ryba_paula/lesson_09_reading_and_writing_files/regex_search.py
students/ryba_paula/lesson_09_reading_and_writing_files/test.txt

Proszę o sprawdzenie :) @kadilak83  (zapomniałam wtedy oznaczyć!)

Add lesson09 solutions

---

students/kaczmarek_katarzyna/lesson_09_reading_and_writing_files/input_file.txt
students/kaczmarek_katarzyna/lesson_09_reading_and_writing_files/mad_libs.py
students/kaczmarek_katarzyna/lesson_09_reading_and_writing_files/mcb.pyw
students/kaczmarek_katarzyna/lesson_09_reading_and_writing_files/regex_search.py

@kadilak83 - Cześć Marcin! Przyszedł weekend i można nadrobić zaległości. Zerknij proszę na lekcję 9. Pozdrawiam, Kasia.

Kadilak83/Lesson 09 - Reading and writing files

---

students/medrek_tomasz/lesson_09_reading_and_writing_files/mad_libs.py
students/medrek_tomasz/lesson_09_reading_and_writing_files/mcb.pyw
students/medrek_tomasz/lesson_09_reading_and_writing_files/regex_search.py

Dear @tomekDiakowTieto 
Thank you,
Tomasz

added lesson 09: reading and writing files

---

students/skowronski_rafal/lesson_09_reading_and_writing_files/mad_libs.py
students/skowronski_rafal/lesson_09_reading_and_writing_files/mcb.pyw
students/skowronski_rafal/lesson_09_reading_and_writing_files/regex_search.py

@tomekDiakowTieto Lesson 09 ready

Tomek diakow tieto/lesson 09 reading and writing files

---

students/mielczarek_szymon/lesson_09_reading_and_writing_files/mad_libs.py
students/mielczarek_szymon/lesson_09_reading_and_writing_files/mcb.pyw
students/mielczarek_szymon/lesson_10_organizing_files/deleting_unneeded_files.py
students/mielczarek_szymon/lesson_10_organizing_files/filling_in_the_gaps.py
students/mielczarek_szymon/lesson_10_organizing_files/selective_copy.py

@kuszcjan: ready, please review
regex_search program skipped as "too obvious".

Add solutions for lesson_11

---

students/bec_lukasz/lesson_03_functions/README.md
students/bec_lukasz/lesson_03_functions/calculator.py
students/bec_lukasz/lesson_03_functions/calculator_refactored.py
students/bec_lukasz/lesson_03_functions/collatz_sequence.py
students/bec_lukasz/lesson_03_functions/exponentiation.py
students/bec_lukasz/lesson_03_functions/fibonacci.py
students/bec_lukasz/lesson_03_functions/length_of_segment.py
students/bec_lukasz/lesson_03_functions/negative_exponent.py

Lesson 3 ready for review @zamber

Added lesson 3 files

---

students/ryba_paula/lesson_10_organizing_files/deleting_unneeded_files.py
students/ryba_paula/lesson_10_organizing_files/filling_the_gaps.py
students/ryba_paula/lesson_10_organizing_files/selective_copy.py

@kadilak83 proszę o sprawdzenie :)
Jeśli chodzi o zadanie z usuwaniem - zrozumiałam, że mamy tylko wyprintować duże pliki, więc to zrobiłam, bez usuwania.

Add lesson 10 solutions

---

students/ryba_paula/lesson_11_argparse_and_math/filling_the_gaps_arg.py
students/ryba_paula/lesson_11_argparse_and_math/regex_search_arg.py
students/ryba_paula/lesson_11_argparse_and_math/selective_copy_arg.py

@kadilak83 proszę o sprawdzenie :)

Add lesson 11 solutions

---

students/jakielczyk_miroslaw/lesson_11_argparse_and_math/filling_in_the_gaps.py
students/jakielczyk_miroslaw/lesson_11_argparse_and_math/regex_search.py
students/jakielczyk_miroslaw/lesson_11_argparse_and_math/selective_copy.py

@kuszcjan please make the review

tasks for lesson_11_argparse_and_math

---

students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/fantasy_game_inventory.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/inspect_args.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson10-cubes.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson10-guess_the_number.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson10-the_number_of_distinct_words_in_some_text.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson11-access_roghts.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson11-countries_and_cities.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/lesson8-uppercase.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/list_to_dictionary_function_for_fantasy_game_inventory.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/logger_wrapper.py
students/sendecki_andrzej/lesson_06_dicts_tuples_sets_args_kwargs/sum_all.py

@kuszcjan 
Please check part 1 of my exercises of lesson 06 - Dictionaries, tuples and sets + *args and **kwargs

lesson_06 exercises - part 1

---

students/mielczarek_szymon/lesson_13_objects_and_classes/circle.py
students/mielczarek_szymon/lesson_13_objects_and_classes/object_inspector_1.py
students/mielczarek_szymon/lesson_13_objects_and_classes/object_inspector_2.py
students/mielczarek_szymon/lesson_13_objects_and_classes/selective_shallow_compare.py

@kuszcjan: ready, please review.
The math for circle program lazily taken from given solution :)

Add solutions for lesson_13

---

students/lakatorz_izaak/lesson_09_reading_and_writing_files/file.txt
students/lakatorz_izaak/lesson_09_reading_and_writing_files/mad_libs.py
students/lakatorz_izaak/lesson_09_reading_and_writing_files/mcb.pyw
students/lakatorz_izaak/lesson_09_reading_and_writing_files/regex_search.py
students/lakatorz_izaak/lesson_09_reading_and_writing_files/result.txt
students/lakatorz_izaak/lesson_09_reading_and_writing_files/test.txt
students/lakatorz_izaak/lesson_09_reading_and_writing_files/test2.txt
students/lakatorz_izaak/lesson_09_reading_and_writing_files/test3.txt

@jedzej please review.
W treści zadania mad libs jest dwa razy noun czy coś w tym stylu. Zmieniłem w kodzie na adverb, jeśli to błąd to prosze o komentarz, zrobię poprawke :)

Lesson 09 solutions

---

students/semko_krzysztof/lesson_09_reading_and_writing_files/extending_the_multiclipboard.pyw
students/semko_krzysztof/lesson_09_reading_and_writing_files/mad_libs.py
students/semko_krzysztof/lesson_09_reading_and_writing_files/regex_search.py
students/semko_krzysztof/lesson_09_reading_and_writing_files/text_file_input.txt

lesson_09_reading_and_writing_files

---

students/ryba_paula/lesson_12_debugging/debugging_coin_toss.py
students/ryba_paula/lesson_12_debugging/validated_user_base.py
students/ryba_paula/lesson_12_debugging/validators.py
students/ryba_paula/lesson_12_debugging/verbose_output.py

@kadilak83 proszę o review
Pierwsze zadanie poprawiłam tylko na tyle, żeby działało. 
Nad trzecim spędziłam ze dwa bite dni, ostatecznie działa (chyba), ale średnio mi się to rozwiązanie podoba - nie mogłam znaleźć nic lepszego. Daj znać :)

Add lesson 12 solutions

---

students/saleta_sebastian/lesson_08_regular_expressions/email_validator.py
students/saleta_sebastian/lesson_08_regular_expressions/phone_number_validator.py
students/saleta_sebastian/lesson_08_regular_expressions/postal_code_validator.py
students/saleta_sebastian/lesson_08_regular_expressions/regex_version_of_strip.py
students/saleta_sebastian/lesson_08_regular_expressions/strong_password_detection.py

Ressult of lesson 08.

---

students/lakatorz_izaak/lesson_10_organizing_files/deleting_unneeded_files.py
students/lakatorz_izaak/lesson_10_organizing_files/filling_in_the_gaps.py
students/lakatorz_izaak/lesson_10_organizing_files/selective_copy.py

Lesson 10 solutions

---

students/jakielczyk_miroslaw/lesson_13_objects_and_classes/circle.py
students/jakielczyk_miroslaw/lesson_13_objects_and_classes/object_inspector_1.py
students/jakielczyk_miroslaw/lesson_13_objects_and_classes/object_inspector_2.py
students/jakielczyk_miroslaw/lesson_13_objects_and_classes/selective_shallow_compare.py

tasks for lesson_13_objects_and_classes

---

students/swietczak_monika/lesson_08_regular_expressions/email_validator.py
students/swietczak_monika/lesson_08_regular_expressions/phone_number_validator.py
students/swietczak_monika/lesson_08_regular_expressions/postal_code_validator.py
students/swietczak_monika/lesson_08_regular_expressions/regex_version_of_strip.py
students/swietczak_monika/lesson_08_regular_expressions/strong_password_detection.py

Added lesson 08 solutions

---

students/urtnowski_daniel/lesson_11_argparse_and_math/filling_in_the_gaps.py
students/urtnowski_daniel/lesson_11_argparse_and_math/helpers.py
students/urtnowski_daniel/lesson_11_argparse_and_math/insert_gaps.py
students/urtnowski_daniel/lesson_11_argparse_and_math/regex_search.py
students/urtnowski_daniel/lesson_11_argparse_and_math/selective_copy.py

@jedzej Lekcja 11 gotowa, proszę o review.

Adding solutions for Lesson 11: argparse + math

---

students/lakatorz_izaak/lesson_11_argparse_and_math/filling_in_the_gaps_argparse.py
students/lakatorz_izaak/lesson_11_argparse_and_math/regex_search_argparse.py
students/lakatorz_izaak/lesson_11_argparse_and_math/selective_copy_argparse.py

Lesson 11 solutions

---

students/semko_krzysztof/lesson_11_argparse/filling_in_the_gaps_argparse.py
students/semko_krzysztof/lesson_11_argparse/regex_search_argparse.py
students/semko_krzysztof/lesson_11_argparse/selective_copy_argparse.py

semko_krzysztof/lesson_11_argparse

---

students/ryba_paula/lesson_14_decorators/access_required.py
students/ryba_paula/lesson_14_decorators/authorization.py
students/ryba_paula/lesson_14_decorators/logged.py
students/ryba_paula/lesson_14_decorators/sort.py

Add lesson 14 solutions

---

students/jakielczyk_miroslaw/lesson_14_decorators/access_required.py
students/jakielczyk_miroslaw/lesson_14_decorators/authorization.py
students/jakielczyk_miroslaw/lesson_14_decorators/logger_wrapper_decorator.py
students/jakielczyk_miroslaw/lesson_14_decorators/sort.py

@kuszcjan please make the review

task for lesson lesson_14_decorators

---

students/mielczarek_szymon/lesson_14_decorators/access_required.py
students/mielczarek_szymon/lesson_14_decorators/authorization.py
students/mielczarek_szymon/lesson_14_decorators/logger.py
students/mielczarek_szymon/lesson_14_decorators/sort.py

@kuszcjan: please review for the last time :)

Add solutions for lesson_14

---

students/semko_krzysztof/lesson_13_objects_and_classes/exercise_one.py
students/semko_krzysztof/lesson_13_objects_and_classes/object_inspectors.py
students/semko_krzysztof/lesson_13_objects_and_classes/selective_shallow_compare.py

semko_krzysztof/lesson_13_objects_and_classes

---

students/semko_krzysztof/lesson_14_decorators/access_required_decorator.py
students/semko_krzysztof/lesson_14_decorators/authorization.py
students/semko_krzysztof/lesson_14_decorators/logged_decorator.py
students/semko_krzysztof/lesson_14_decorators/sort_decorator.py

semko_krzysztof/lesson_14_decorators

---

students/hyska_monika/lesson_13_object_and_classes/exercise1_circle.py
students/hyska_monika/lesson_13_object_and_classes/object_inspector_1.py
students/hyska_monika/lesson_13_object_and_classes/object_inspector_2.py
students/hyska_monika/lesson_13_object_and_classes/selective_shallow_compare.py

lesson_13_Monika_Hyska

---

students/swietczak_monika/lesson_10_organizing_files/deleting_unneeded_files.py
students/swietczak_monika/lesson_10_organizing_files/filling_the_gaps.py
students/swietczak_monika/lesson_10_organizing_files/selective_copy.py

@adziu lesson10 ready for review.

Added lesson 10 solutions

---

students/swietczak_monika/lesson_11_argparse_and_math/filling_the_gaps_argparse.py
students/swietczak_monika/lesson_11_argparse_and_math/regex_search_argparse.py
students/swietczak_monika/lesson_11_argparse_and_math/selective_copy_argparse.py

@adziu Lesson 11 ready for review.

Added lesson 11 solutions

---

students/skowronski_rafal/lesson_10_organizing_files/deleting_unneeded_files.py
students/skowronski_rafal/lesson_10_organizing_files/filling_in_the_gaps.py
students/skowronski_rafal/lesson_10_organizing_files/selective_copy.py

@tomekDiakowTieto Lesson 10 ready

Add Lesson 10: organizing files

---

students/adam_wulw/lesson_08_regular_expressions/email_validator.py
students/adam_wulw/lesson_08_regular_expressions/phone_number_validator.py
students/adam_wulw/lesson_08_regular_expressions/postcode_validator.py
students/adam_wulw/lesson_08_regular_expressions/strip.py
students/adam_wulw/lesson_08_regular_expressions/strong_password.py

All lesson 8

---

students/medrek_tomasz/lesson_10_organizing_files/deleting_unneded_files.py
students/medrek_tomasz/lesson_10_organizing_files/filling_in_the_gaps.py
students/medrek_tomasz/lesson_10_organizing_files/inserting_in_the_gaps.py
students/medrek_tomasz/lesson_10_organizing_files/selective_copy.py

Dear @tomekDiakowTieto ,
Thank you,
Tomasz

added lesson 10: organizing files

---

students/skowronski_rafal/lesson_11_argparse_and_math/filling_in_the_gaps.py
students/skowronski_rafal/lesson_11_argparse_and_math/regex_search.py
students/skowronski_rafal/lesson_11_argparse_and_math/selective_copy.py

@tomekDiakowTieto Lesson 11 ready

Add 'Lesson 11 - argparse + math'

---

students/medrek_tomasz/lesson_11_argparse/filling_in_the_gaps.py
students/medrek_tomasz/lesson_11_argparse/regex_search.py
students/medrek_tomasz/lesson_11_argparse/selective_copy.py

Dear @tomekDiakowTieto ,
Thanks,
Tomasz

added lesson 11: argparse

---

students/skowronski_rafal/lesson_12_debugging/coin_toss.py
students/skowronski_rafal/lesson_12_debugging/regex.py
students/skowronski_rafal/lesson_12_debugging/regex_search.py
students/skowronski_rafal/lesson_12_debugging/user_base.py

@tomekDiakowTieto: Lesson 12 ready

Added Lesson 12: debugging

---

students/skowronski_rafal/lesson_13_objects_and_classes/circles.py
students/skowronski_rafal/lesson_13_objects_and_classes/object_inspector.py
students/skowronski_rafal/lesson_13_objects_and_classes/shalow_compare.py
students/skowronski_rafal/lesson_13_objects_and_classes/test_circles.py

@tomekDiakowTieto Lesson 13 added

Add 'Lesson 13 - Objects and classes'

---

students/skowronski_rafal/lesson_14_decorators/project_01_sort/sort.py
students/skowronski_rafal/lesson_14_decorators/project_01_sort/test_sort.py
students/skowronski_rafal/lesson_14_decorators/project_02_access_required/authorization.py
students/skowronski_rafal/lesson_14_decorators/project_02_access_required/restrictions.py
students/skowronski_rafal/lesson_14_decorators/project_02_access_required/test_restrictions.py
students/skowronski_rafal/lesson_14_decorators/project_03_logger/logger.py
students/skowronski_rafal/lesson_14_decorators/project_03_logger/logger_wrapper.py

@tomekDiakowTieto: added lesson 14

Lesson 14 - Decorators
